### ISSUE TITLE
Console Error on Windows: 'Module has no attribute symlink'

### ISSUE THREAD

**Issue by dhstack** [Shopify/shopify_python_api#104]
After succesfully configuring the yaml file (after applying fix proposed in issue #103), I got the symlink error on Windows.

Looks like this might be a potential fix (add to top of shopify_api.py):
```
if os.name == "nt":
    def symlink_ms(source, link_name):
        import ctypes
        csl = ctypes.windll.kernel32.CreateSymbolicLinkW
        csl.argtypes = (ctypes.c_wchar_p, ctypes.c_wchar_p, ctypes.c_uint32)
        csl.restype = ctypes.c_ubyte
        flags = 1 if os.path.isdir(source) else 0
        try:
            if csl(link_name, source.replace('/', '\\'), flags) == 0:
                raise ctypes.WinError()
        except:
            pass
    os.symlink = symlink_ms
```
[Fix Source](https://stackoverflow.com/questions/6260149/os-symlink-support-in-windows)
Needs to be tested further.

**Comment by kevinhughes27** [comment]
are you able to test these?

**Comment by dhstack** [comment]
I put the code above in my code and it worked. However, I ended up just using my own console to test shopify.

For issue #103 that proposed fix works and is needed to even get the console up and running.

**Comment by kevinhughes27** [comment]
I mean test that it still works on the other OSes

**Comment by dhstack** [comment]
Ah, I am not able to test on other OSes as I only have Windows machines

**Comment by asiviero** [comment]
All tests passed on Linux

**Comment by kevinhughes27** [comment]
The issue that the cli is not tested by the test suite someone has to just use it (or write a test suite for it). We actually removed the cli from the ruby gem since it was sort of a separate thing

**Comment by asiviero** [comment]
Alright, I can take a look at that as well

**Comment by kevinhughes27** [comment]
Thanks!

**Comment by asiviero** [comment]
I was able to create a product from the console with that fix. I guess it should work for most uses since it looks like sugar to some boring set up tasks. I'll take a look at the ruby test suite so I can be more certain on that.

**Comment by kevinhughes27** [comment]
sweet thanks.
