### ISSUE TITLE
Cannot duplicate product with multiple options if first option has only one variant.

### ISSUE THREAD

**Issue by danblaker** [Shopify/shopify_python_api#106]
This is a strange one. If a product has multiple options and the first option only has a single variant, that product cannot be duplicated to a new product via the Python API. If the first option has multiple variants, no problem. If the options are reordered so the single-variant option is second, no problem.

Here's what my test product looks like: 
![screen shot 2015-08-04 at 6 47 39 pm](https://cloud.githubusercontent.com/assets/9521/9076596/541ef95c-3ad9-11e5-94c2-397d0bda18da.png)

It has a single Size variant and two Color variants, in that order. Here's how to reproduce the issue in shopify_api.py console:

```
>>> test_product = shopify.Product.find(1744898049)
>>> test_product.variants
[variant(5308899457), variant(5309143745)]
>>> test_product.variants[0].attributes
{u'weight': 0.0, u'requires_shipping': True, u'updated_at': u'2015-08-04T21:45:50-04:00', u'inventory_quantity': 1, u'compare_at_price': None, u'id': 5308899457, u'sku': u'', u'title': u'Big / Red', u'inventory_policy': u'deny', u'inventory_management': None, u'fulfillment_service': u'manual', u'option2': u'Red', u'option3': None, u'weight_unit': u'lb', u'option1': u'Big', u'price': u'80.00', u'barcode': u'', u'image_id': None, u'taxable': True, u'old_inventory_quantity': 1, u'grams': 0, u'created_at': u'2015-08-04T21:42:00-04:00', u'position': 1}
>>> test_product.variants[1].attributes
{u'weight': 0.0, u'requires_shipping': True, u'updated_at': u'2015-08-04T21:46:04-04:00', u'inventory_quantity': 1, u'compare_at_price': None, u'id': 5309143745, u'sku': u'', u'title': u'Big / Blue', u'inventory_policy': u'deny', u'inventory_management': None, u'fulfillment_service': u'manual', u'option2': u'Blue', u'option3': None, u'weight_unit': u'lb', u'option1': u'Big', u'price': u'80.00', u'barcode': u'', u'image_id': None, u'taxable': True, u'old_inventory_quantity': 1, u'grams': 0, u'created_at': u'2015-08-04T21:46:04-04:00', u'position': 1}
>>> new_product = shopify.Product()
>>> new_product.title = 'New Product'
>>> new_product.variants = test_product.variants
>>> new_product.save()
False
```

**Comment by danblaker** [comment]
I just noticed that the 'position' attribute is set to 1 for both variants. I'm guessing that's the root of this issue, but I'm ready to hop out of this particular rabbit hole and move on!

**Comment by kevinhughes27** [comment]
If you type `product.errors` you can see why the save failed. It may also be related to the way you copied them - these variants will have IDs of variants belonging to other products.

**Comment by danblaker** [comment]
Not an issue. Turns out the error was due to my not copying over the template_product.options in addition to the variants. Sheesh.

It doesn't seem to matter a bit that I'm saving variants with existing IDs; Shopify gives the variants new IDs upon product.save().
