### ISSUE TITLE
Cannot create new Product options or copy existing ones.

### ISSUE THREAD

**Issue by richard-li** [Shopify/shopify_python_api#107]
So I seem to be getting this issue where I cannot create new product options or copying existing ones. Both give me the error `<pyactiveresource.activeresource.Errors object at 0x107173110>`

On python 2.7.6, shopify 2.1.3, shopifyAPI 2.1.5, pyactiveresource 2.1.2

How to reproduce the issue in console by copying existing product:
Here are the options: ![Image of options](http://i.imgur.com/e2zx8BK.png)
```
>>> products = shopify.Product.find()
>>> new_product = shopify.Product()
>>> new_product.title = 'test'
>>> new_product.body_html = 'asdfasdf'
>>> new_product.product_type = 'T-shirt'
>>> new_product.vendor = 'vendor'
>>> new_product.options = products[0].options
>>> new_product.save()
False
```
And to reproduce by creating new options:
```
>>> new_product = shopify.Product()
>>> new_product.title = 'test'
>>> new_product.body_html = 'asdfasdf'
>>> new_product.product_type = 'T-shirt'
>>> new_product.vendor = 'vendor'
>>> new_product.options = [{"name": "Style"}, {"name": "Size"}]
>>> new_product.save()
False

**Comment by kevinhughes27** [comment]
can you print what the error message is?

**Comment by richard-li** [comment]
`<pyactiveresource.activeresource.Errors object at 0x107173110>`

**Comment by kevinhughes27** [comment]
yeah but if you look at that object it will say exactly what the error is

**Comment by richard-li** [comment]
How would I do that?

**Comment by kevinhughes27** [comment]
try `. full_messages`

**Comment by richard-li** [comment]
`new_product.errors.full_messages`

returns

`<bound method Errors.full_messages of <pyactiveresource.activeresource.Errors object at 0x110516890>>`

**Comment by kevinhughes27** [comment]
woops not 100% clear instructions - its a method so you need to actually call it `.full_messages()`

**Comment by richard-li** [comment]
[u'1 option values given but 2 options exist', u'cannot be blank'] - That is the error that I get for both scenarios.

**Comment by kevinhughes27** [comment]
yeah so that is because your product variant has 2 options but you are only supplying the first one - it can't guess what to do with the second.

Since this isn't an issue with the code of shopify_python_api I am going to close this issue. The shopify api forums is a more appropriate place to post questions and ask for helping using the api https://ecommerce.shopify.com/c/shopify-apis-and-technology
