### ISSUE TITLE
Unable to do shopify.Webhook.post 

### ISSUE THREAD

**Issue by iamkhush** [Shopify/shopify_python_api#111]
I need to POST to /admin/webhooks.json. I use 

``shopify.Webhook.post('',json.dumps(json_data))`` which uses  `_class_post` which uses this url format - 

`'%(prefix)s/%(plural)s/%(method_name)s.%(format)s%(query)s'`   (_custom_method_collection_url)

However for POST request needed is  '%(prefix)s/%(plural)s.%(format)s%(query)s'  (_collection_path)

**Comment by gavinballard** [comment]
You shouldn't need to be calling `post()` methods directly - try instantiating a new Webhook instance then calling `save`, something like this:

```python
new_webhook = shopify.Webhook()
new_webhook.address = 'https://www.example.com'
new_webhook.topic = 'orders/create'
new_webhook.save()
```

**Comment by iamkhush** [comment]
What does calling save do? Does it fire the webhook request?

**Comment by akhtariali** [comment]
> You shouldn't need to be calling `post()` methods directly - try instantiating a new Webhook instance then calling `save`, something like this:
> 
> ```python
> new_webhook = shopify.Webhook()
> new_webhook.address = 'https://www.example.com'
> new_webhook.topic = 'orders/create'
> new_webhook.save()
> ```

It shouldn't take a dive into Issues to find these four lines of code. This library, while powerful, is criminally under-documented.
