### ISSUE TITLE
How do I retrieve Location information?

### ISSUE THREAD

**Issue by finoptimal-dev** [Shopify/shopify_python_api#113]
I see that dir(shopify) doesn't show me Location as an attribute, but I'm wondering if there's another way to use the API to get it (even though perhaps it's not wrapped as nicely as these other resources):

https://docs.shopify.com/api/location

dir(shopify)
['Address', 'ApplicationCharge', 'Article', 'Asset', 'BillingAddress', 'Blog', 'CarrierService', 'Cart', 'Checkout', 'Collect', 'Comment', 'Country', 'CustomCollection', 'Customer', 'CustomerGroup', 'CustomerSavedSearch', 'Event', 'Fulfillment', 'FulfillmentService', 'GiftCard', 'Image', 'LineItem', 'Metafield', 'NoteAttribute', 'Option', 'Order', 'OrderRisk', 'Page', 'PaymentDetails', 'Policy', 'Product', 'ProductSearchEngine', 'Province', 'Receipt', 'RecurringApplicationCharge', 'Redirect', 'Rule', 'ScriptTag', 'Session', 'ShippingAddress', 'ShippingLine', 'Shop', 'ShopifyResource', 'SmartCollection', 'TaxLine', 'Theme', 'Transaction', 'VERSION', 'ValidationException', 'Variant', 'Webhook', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'address', 'application_charge', 'article', 'asset', 'base', 'billing_address', 'blog', 'carrier_service', 'cart', 'checkout', 'collect', 'comment', 'country', 'custom_collection', 'customer', 'customer_group', 'customer_saved_search', 'event', 'fulfillment', 'fulfillment_service', 'gift_card', 'image', 'line_item', 'metafield', 'mixins', 'note_attribute', 'option', 'order', 'order_risk', 'page', 'payment_details', 'policy', 'product', 'product_search_engine', 'province', 'receipt', 'recurring_application_charge', 'redirect', 'resources', 'rule', 'script_tag', 'session', 'shipping_address', 'shipping_line', 'shop', 'smart_collection', 'tax_line', 'theme', 'transaction', 'variant', 'version', 'webhook', 'yamlobjects']

Can I use this module to get location information?

Thanks!

**Comment by kevinhughes27** [comment]
looks like we are just missing the module. If you look at any of the resource classes they are super simple. If you add it please submit the PR. @ShayneP maybe you can add this

**Comment by jakeparis** [comment]
@kevinhughes27 I'm not sure why this was closed, as only a stub `Location` class was added. Do you have any idea on when a fully-fleshed out method of getting the location will be available?

Unless I'm using things wrong, that's possible too... Thanks!

**Comment by kevinhughes27** [comment]
A lot of the classes are like that - doesn't mean they don't work. It just doesn't need anything special other than the defaults.
