### ISSUE TITLE
Missing Plus modules

### ISSUE THREAD

**Issue by ifnull** [Shopify/shopify_python_api#115]
`User` and `Discount` seem to be missing from the Python API. Interestingly `GiftCard` is included.

**Comment by gavinballard** [comment]
I added the `GiftCard` resource as I needed it for a client project. As you can see from the [pull request](https://github.com/Shopify/shopify_python_api/pull/99), it's not too difficult to add support for additional resources as needed :).

**Comment by ifnull** [comment]
@gavinballard I was just looking at that. I added Discount and I am testing now.

**Comment by ifnull** [comment]
Discount added in https://github.com/Shopify/shopify_python_api/pull/116 pull request.
