### ISSUE TITLE
Right way to set state

### ISSUE THREAD

**Issue by cdvv7788** [Shopify/shopify_python_api#119]
Docs mention that state is important and what it should be, however it is not mentioned how to add it to the url. I ended up appending it by hand (&state=some-state-here) because i didn't find a way to do it with the app. Is there a better way to do this?

**Comment by kevinhughes27** [comment]
I don't understand your question - what exactly are you trying to do?

**Comment by cdvv7788** [comment]
state – Optional – A randomly selected value provided by your application, which is unique for each authorization request. During the OAuth callback phase, your application must check that this value matches the one you provided during authorization. This mechanism is important for the security of your application.
I have that working already, just wondering if there is a better way.

**Comment by kevinhughes27** [comment]
Yeah that is probably best - you could also add it in here https://github.com/Shopify/shopify_python_api/blob/master/shopify/session.py

**Comment by dylanahsmith** [comment]
I agree that this really isn't clear.  Pull #108 updated the README.md to say "This mechanism is important for the security of your application", yet we don't even have an optional keyword argument on create_permission_url to easily provide it, nor do we provide the state argument in the example code.
