### ISSUE TITLE
Have deleted an order through API but am able to find it still through API ? Is there a reason?

### ISSUE THREAD

**Issue by skalfyfan** [Shopify/shopify_python_api#120]
Am implementing a private app using the API and I've generated a couple orders. Am now implementing the functionality to delete these "api generated" orders if required.

I'm using:

    try:
       order = shopify.Order.find(int(order_number))
       #order.cancel()
       print("Attempting to delete order #: " + order_number)
       order.destroy()
    except:
       ....

This appears to work and the order is getting deleted in the front-end Shopify dashboard. However, through the API I am **still** able to retrieve the order data for the order I apparently just deleted?! Why is this? 

E.g. I can still call:  *order = shopify.Order.find(int(order_number))*, where *order_number* is the id I just deleted. It will retrieve an order object with all the data that I apparently just deleted. Some kind of soft deletion caching going on? Will I no longer be able to retrieve this after a day or two?

Is *destory()* the correct method to be calling to delete an order in the system? Or should we be calling something such as *order.delete()*, where we may actually receive a connection response which we can then check?

Also, I can still see the order data when navigating my web browser to:
*https://API_KEY:API_PASS@mystore.myshopify.com/admin/orders/order_number.json*

Shouldn't it be deleted and gone?

Is there a way through the API to verify if the order object has already been deleted (through API) ?

This issue is similar to the following post which never seemed to get a response on whether it in fact was an issue/bug or a feature ? 
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/shopify-api-how-does-order-deletion-work-221931

P.S do we still need to cancel an order before deleting it (like you do in the admin dashboard?) or through the API can we directly delete an order the cancellation is automated?

Thanks!

Paul

**Comment by kevinhughes27** [comment]
You should be using delete which hits the server and lets you know that the request was processed properly.

We do have some slightly different caching in place for the admin vs the api. If they are not appearing from the admin then they are gone and the JSON will not be available soon.
