### ISSUE TITLE
[REQUEST] Possible to add `test` attribute for orders to the API?

### ISSUE THREAD

**Issue by skalfyfan** [Shopify/shopify_python_api#121]
An order object contains an attribute `test` which (i assume) signifies whether an order was made in test mode (i.e. testing shopify payments - https://docs.shopify.com/manual/more/shopify-payments/testing-shopify-payments). 

This attribute retains a value of either True or False and when testing payment gateway through the dashboard (i.e placing an order through front-end using credit card test info) the resulting order will *clearly* state on the order that *this order was placed in test mode*.

Would it be possible to add this configuration option to the Shopify API? I'm playing with testing an application currently and would like to have my generated *test* orders have this flag set to to True. It appears that this attribute is not currently supported through the API and not allowed to be set?

Unless I'm doing it wrong? Currently I'm setting my generated orders as so:

```python
order = {
  'customer': customer_data,
  'test': True
  'line_items': cls.line_items_generate()
}

shopify.Orders().create(order)

```

The order is generated, and everything works, except the `test` attribute is being completely ignored and is always set to False when generating an order through the API. I've double checked the saved generated order numerous times and the `test` attribute is always False even though I have explicitly attempted to set it's value.

**Comment by kevinhughes27** [comment]
This question will get more attention on the Shopify forums https://ecommerce.shopify.com/c/shopify-apis-and-technology since its not necessarily a bug with the python library specifically

**Comment by anka-sirota** [comment]
@skalfyfan Did you manage to figure out the issue yet? I couldn't find relevant questions on the Shopify forums, so I've posted one:

https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/test-attribute-is-ignored-when-posting-a-new-order-via-api-299683

**Comment by skalfyfan** [comment]
@anka-sirota no resolution to the issue unfortunately. We had a client with a paid account already set up so we just kept their store under password protection and continued generating orders for testing purposes.

Thanks for making the full post on the ecommerce forums. I imagine we'll run into this issue again on a Shopify dev shop sometime in the future since there are order limits on the dev shops.
