### ISSUE TITLE
Add destroy example to README?

### ISSUE THREAD

**Issue by tbloncar** [Shopify/shopify_python_api#122]
Thoughts on adding a `destroy` example to the README? I made the mistake of looking for a one-to-one mapping between [documented API endpoints](https://docs.shopify.com/api/order) and [resource implementations](https://github.com/Shopify/shopify_python_api/blob/master/shopify/resources/order.py) when working with Order records, and since I hadn't worked with pyactiveresource before, it wasn't especially clear that `destroy` would just work. Definitely some ignorance on my part, but I think even seeing the following in the README would've obviated the digging.

    # Remove a product
    product.destroy()

**Comment by kevinhughes27** [comment]
yeah I would be 100% okay with that. I usually check the tests for methods in this repo when I forget them but admittedly we don't have amazing coverage here. The article test is a good example iirc.

**Comment by tbloncar** [comment]
Okay. Great. Thanks for the info.
