### ISSUE TITLE
Authenticate multiple private apps in single thread

### ISSUE THREAD

**Issue by flux627** [Shopify/shopify_python_api#123]
I know that the session variables are thread-safe, however is it possible to somehow attach different private app authentications to separate objects in the same thread? Since authentication is attached to the module object itself, I can't seem to figure it out. Is this possible with this module?

**Comment by kevinhughes27** [comment]
This method is probably your best bet: https://github.com/Shopify/shopify_python_api/blob/master/shopify/session.py#L30

You can also just set the session to what you need, use the api client and then set it to the next shop.
