### ISSUE TITLE
Acces to X-Shopify-Shop-Api-Call-Limit response header

### ISSUE THREAD

**Issue by jbub** [Shopify/shopify_python_api#125]
As per https://docs.shopify.com/api/introduction/api-call-limit, we need a way to access "X-Shopify-Shop-Api-Call-Limit" response header to be able to use the api correctly. Or is there a way already ?

**Comment by kevinhughes27** [comment]
you should be able to do so already. Have a look at how we implemented for the ruby api. https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/limits.rb.

I am going to close this - reopen if this is not possible with pyactiveresource

**Comment by jbub** [comment]
Okay i was able to find the reponse header like this:

`shop._threadlocal.connection.response.headers['x-shopify-shop-api-call-limit']`. 

Dont know if this is the best way, but it is working.

**Comment by kevinhughes27** [comment]
It might be nice to make a helper method to access this so you don't need to reach so far each time to get the header. Otherwise this looks good so I will leave closed.
