### ISSUE TITLE
errors field sometimes contains a string instead of an object

### ISSUE THREAD

**Issue by dasony** [Shopify/shopify_python_api#127]
When saving a new Order object, I get following an error.

```
Traceback (most recent call last):
  File "???", line ???, in create_shopify_order
    shopify_order.save()
  File "/usr/local/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 833, in save
    self.errors.from_json(err.response.body)
  File "/usr/local/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 130, in from_json
    self.from_hash(errors)
  File "/usr/local/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 87, in from_hash
    for key, errors in six.iteritems(messages):
  File "/usr/local/lib/python2.7/site-packages/six.py", line 576, in iteritems
    return iter(d.iteritems(**kw))
AttributeError: 'unicode' object has no attribute 'iteritems'
```

When I printed out err.response.body, I got the following.

`{"errors":"Inventory not available; Asked for {654.....=\u003e1}, got {654....=\u003e0}"}`

I think either the API or the python module should be fixed. Thanks.

**Comment by kevinhughes27** [comment]
@jamiemtdwyer can you investigate here? It would be good to start with determining if the response from Shopify is malformed

**Comment by jamiemtdwyer** [comment]
Related to https://github.com/Shopify/shopify_api/issues/103, a similar fix to https://github.com/Shopify/shopify_api/pull/107 will need to be deployed here. will look into this shortly

**Comment by bstjepanovic1** [comment]
I got same error when saving order with small difference in response:

```
pyactiveresource.connection.ResourceInvalid: Response(code=422, body="b'{"errors":"Unable to claim inventory"}'"
```
Is this same error or am I doing something wrong? Thanks

**Comment by dave4jr** [comment]
@jamiemtdwyer Jamie, this issue has existed since 2015, you guys said there needed to be a fix deployed, but then it just fell off. Can we please have an idea of what the current status of this is? Would really appreciate it. Thanks.
