### ISSUE TITLE
Confusing Documentation on Github Readme

### ISSUE THREAD

**Issue by hairyjerry** [Shopify/shopify_python_api#137]
The documentation available on the readme is very confusing. 

For example, after setting up proper authentication, the first example presented is: 
`shop = shopify.Shop.current()`

In the rest of the example the variable `shop` is never used and there's no explanation of what this line does or why it's necessary (is it necessary?)

Additionally it's stated that everything is returned as an `ActiveResource`, with no explanation of what that is, what it offers, or how it affects how the api should be used.

For many, this README is the first and only point of information for usage of this library, and some more clarity in the documentation would go a long way. Please consider revamping the README so us shopify newbies can get up to speed faster 😄 

Right now I'm balancing whether I'd rather read the code to figure this out or open source an easier to use api.

**Comment by hairyjerry** [comment]
ping @kevinhughes27 @dylanahsmith @gavinballard

**Comment by hairyjerry** [comment]
https://github.com/Shopify/shopify_python_api/issues/132

**Comment by kevinhughes27** [comment]
This `shop = shopify.Shop.current()` is just an example of how to fetch the current shop. I added a note in that code block about this.

I also added a link to active resource above that same example.

You're best bet is to read the tests and then start making API calls. If you find any other inconsistencies or have doc suggestions please let us know.

**Comment by hairyjerry** [comment]
Thanks for the quick response @kevinhughes27 

I found myself frustrated getting started this morning and I apologize for the ranty issue here. 

I'll give things an honest try and report back 😄

**Comment by kevinhughes27** [comment]
Thanks! I deffs agree that the docs here aren't the best. The good news though is since every object is just active resource after you've written a few calls it should be smooth sailing since its all the same.

**Comment by mkeegan** [comment]
I've put together a [cheatsheet](https://paper.dropbox.com/doc/Shopify-Python-API-Cheatsheet-SILqbyNEQzounC3O22vJu) using the test cases in the repository. Hope they'll put people on the right track.

**Comment by kevinhughes27** [comment]
Looks pretty good! I would be happy to merge something like this to a markdown file in the repo

**Comment by mkeegan** [comment]
Fortunately Dropbox Paper can convert into markdown! File attached.

[Shopify-Python-API-Cheatsheet.md.zip](https://github.com/Shopify/shopify_python_api/files/397420/Shopify-Python-API-Cheatsheet.md.zip)
