### ISSUE TITLE
shopify.Article.find(blog_id=xxx, limit=50, page=zzz) returns duplicate articles

### ISSUE THREAD

**Issue by hieu-n** [Shopify/shopify_python_api#139]
I have 221 articles. The code below returns 221 articles but duplicate, only 169 unique articles.

```
existing_articles = []
for i in xrange(1, 6):
    existing_artciles.extend(shopify.Article.find(blog_id=the_blog.id, limit=50, page=i))
len(existing_articles)
#211
len(set([a.id for a in existing_articles]))
#169
```

**Comment by jamiemtdwyer** [comment]
Pagination in the API is admittedly a bit wonky sometimes. I suggest using `since_id` over `page` whenever possible.

Either way, this isn't something we can solve at the level of this package.
