### ISSUE TITLE
refunds missing

### ISSUE THREAD

**Issue by pmtolk** [Shopify/shopify_python_api#143]
I noticed that ruby has a refund object however this is missing from the python api

https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/refund.rb

How can I create a refund using the python api?

**Comment by kevinhughes27** [comment]
If this lib is missing a resource you can just add it!

**Comment by pmtolk** [comment]
How can I create a refund using the python api?

**Comment by jamiemtdwyer** [comment]
Hey pmtolk,

This is a fairly new endpoint and hasn't been added to the Python library. For now, you would have to roll your own solution based on the API reference [here](https://help.shopify.com/api/reference/refund). I'll try to have this functionality added to the library in the very near future, unless someone beats me to it.

**Comment by jamiemtdwyer** [comment]
Refunds added in release 2.1.6
