### ISSUE TITLE
timeline_comments

### ISSUE THREAD

**Issue by pmtolk** [Shopify/shopify_python_api#144]
How can I get and post timeline comments for an order?

https://fragrantjewels.myshopify.com/admin/orders/ORDER_ID/timeline_comments

they do not appear to be in the order.json and when I view the above url it has some weird looking stuff

**Comment by jamiemtdwyer** [comment]
Timeline isn't currently accessible through the API, however it is on the roadmap. Once this functionality has been added to the API, we'll update this library accordingly.
