### ISSUE TITLE
Gift cards cannot be expired

### ISSUE THREAD

**Issue by iandouglas** [Shopify/shopify_python_api#145]
Per chat with support back in February 2016, there's no expiry possible on gift cards using this library, which is pretty important to implement. As of writing this issue, no progress has been made on this.

**Comment by jamiemtdwyer** [comment]
Gift cards can be created with expiry dates, see the following example:

```python
gc = shopify.GiftCard.create({'initial_value': 25.0, 'expires_on': "2020-01-01"})
```
