### ISSUE TITLE
Attaching Images - Decode required for Python 3 compatibility

### ISSUE THREAD

**Issue by pntt** [Shopify/shopify_python_api#147]
When attaching an image from a local file:

```
with open("some_image.jpg","rb") as f:
    img = f.read()
    image1.attach_image(data=img)
```

img will be bytes while the attachment needs to be a string to the JSONified. So in image.py:

```
def attach_image(self, data, filename=None):
    self.attributes["attachment"] = base64.b64encode(data).decode() #decode() for Python 3
    if filename:
        self.attributes["filename"] = filename
```

I am not sure how to keep it Python 2 compatible.

**Comment by ressy** [comment]
I ran into this as well just now, but adding the `.decode()` isn't fixing it for me in Python 3.  In Python 2.6 onward `bytes` is a synonym for `str`, and `str` has a decode method, so it seems to me like it should work either way.  But when I tried this myself with 3.5 I still get an error in pyactiveresource complaining that it can't JSON-encode a bytes object.  So maybe PyActiveResource is casting the base64 string back into bytes somewhere along the line?

**Comment by ressy** [comment]
Never mind, it works just as pntt described.  (I was mixing up my paths and editing the version of image.py for Python 2.7 while trying to test it in 3.5.)  So, that one-line change looks to fix the problem and runs fine for me in both Python versions.
