### ISSUE TITLE
Security verification/HMAC

### ISSUE THREAD

**Issue by merstech** [Shopify/shopify_python_api#151]
We are having trouble with our app install after the HMAC updates by Shopify.

The Shopify Python API handles the security verification when Shopify redirects a merchant that is looking to install our app. It was working before Shopify announced the final removal of "signature" from the redirect URL. Now our install doesn't work.

Since the security verification is handled by the API, we don't have much visibility as to why the security step is broken.

Is this a known issue?

**Comment by kevinhughes27** [comment]
perhaps the issue is here? https://github.com/Shopify/shopify_python_api/blob/master/shopify/session.py#L139

You are using this class to verify the hmac signature? I would recommend testing your local install and checking out how this function behaves.

**Comment by jamiemtdwyer** [comment]
Hi merstech,

This library has not supported MD5 signature validation for over 18 months. If you are using a version > 2.1.1, you should not experience any implications due to the MD5 signature validation mechanism being deprecated.
