### ISSUE TITLE
ShippingZone is missing from 2.1.5 release

### ISSUE THREAD

**Issue by pbojinov** [Shopify/shopify_python_api#152]
Steps to reproduce:

1. Install using instructions provided: `pip install --upgrade ShopifyAPI`
2. Go to folder (different depending on your system) where pip installs ShopifyAPI and look for `shipping_zone` in /resources folder.
3. `shipping_zone` is not in resources folder of the 2.1.5 release.

You can also verify by trying to use ShippingZone in a small snippet and you'll get the following error since it does not exist: `AttributeError: 'module' object has no attribute 'ShippingZone'`

```python
import shopify
store_url = '[redacted]'
store_token = '[redacted]'
session = shopify.Session(store_url, store_token)
shopify.ShopifyResource.activate_session(session)
items = shopify.ShippingZone.find()
```

![image](https://cloud.githubusercontent.com/assets/709616/17631649/c980c33a-6079-11e6-8d19-27d6f9a9034f.png)

**Comment by pbojinov** [comment]
Looks like it's in 2.1.6, but 2.1.6 isn't on PyPi. Should be an easy fix. Any particular reason why 2.1.6 isn't up on https://pypi.python.org/pypi/ShopifyAPI?

**Comment by maximebedard** [comment]
@ShayneP @kevinhughes27 Is it up to you guys to push the changes onto pypi repo?

**Comment by pbojinov** [comment]
A workaround is to install from master using: `sudo pip install git+https://github.com/Shopify/shopify_python_api.git`

**Comment by kevinhughes27** [comment]
Anyone should be able to using shipit

**Comment by maximebedard** [comment]
👍

**Comment by pbojinov** [comment]
@kevinhughes27 can you clarify what you mean? I'm not familiar with `shipit` or how to use it.

Are you able to deploy the latest version of the project to pip? Or is there anything I can do to help deploy it. I can open up a PR.

**Comment by maximebedard** [comment]
No worries Petar, shipit is our internal tool that we use for deployment. I'll deploy to the latest version first thing tomorrow.

**Comment by pbojinov** [comment]
@maximebedard perfect, thank you!
