### ISSUE TITLE
def create_permission_url(self, scope, redirect_uri=None) redirect_uri is required now.

### ISSUE THREAD

**Issue by marcvanolmen** [Shopify/shopify_python_api#153]
I feel the def create_permission_url(self, scope, redirect_uri=None)  https://github.com/Shopify/shopify_python_api/blob/master/shopify/session.py is saying required now in the documentation I feel the API Should reflect that.

**Comment by kevinhughes27** [comment]
If I am following correctly should we not just remove the default argument of None?

**Comment by marcvanolmen** [comment]
Indeed, and if you look at the related ticket: #154 needs to add State=None parameter I think and add that to URL.

**Comment by kevinhughes27** [comment]
Sounds good to me!
