### ISSUE TITLE
Shopify Plus rate limit?

### ISSUE THREAD

**Issue by lowfatcode** [Shopify/shopify_python_api#155]
Using the Python API I can only seem to get around 1 request/second (specifically this is a request for a single OrderRisk, so nothing heavyweight).

Having a dig around I can't seem to see anything in the code base of this library enforcing a rate limit, is this genuinely the response time from the Shopify API endpoint?

Inspecting the X-Shopify-Shop-Api-Call-Limit header it is always coming back as "1/80".

**Comment by jamiemtdwyer** [comment]
Hey lowfatcode,

These rates are enforced by Shopify rather than the API library.
