### ISSUE TITLE
Helper method for uninstalling app

### ISSUE THREAD

**Issue by josefdlange** [Shopify/shopify_python_api#158]
Howdy!

Love this library. Really make integrating with Shopify easy as pie. [Shopify docs](https://help.shopify.com/api/guides/authentication/uninstalling-applications) indicate that it's possible to programmatically uninstall an app by issuing a `DELETE` to `https://someshop.myshopify.com/admin/api_permissions/current.json` (authenticated of course). I know I can do this on my own without any helpers, per se, but it'd be nice to see a helper method somewhere.

I'd be glad to spit out an implementation, but I wanted some guidance and opinions: would it be necessary to define a new resource, or would it be reasonable -- if not a little hacky -- to bolt it onto `shopify.Session` or something?

Let me know what y'all think.

**Comment by kevinhughes27** [comment]
I haven't looked in here recent enough to have much of an opinion there. I would say do it whichever way you think looks cleaner and then document the feature in the readme.

**Comment by josefdlange** [comment]
I'm going to have to do a deep dive on `pyactiveresource` to understand all of the moving pieces. I don't have a Ruby background and so it'll be a little interesting.

I'll posit a couple solutions eventually.
