### ISSUE TITLE
Product Save

### ISSUE THREAD

**Issue by delphinian** [Shopify/shopify_python_api#162]
Is it possible to extend the Product.Save() function beyond the basic boolean? Possibility using error codes such as the HTTP coding format?

I have two products, and one when saved is returned true, and the other false. The products are complete in their data structures. A response code would be easier on the troubleshooting of why the second product fails.

Thanks

**Comment by paladinlogic** [comment]
I just ran into that too. If you check Product.errors.full_messages() you will see the errors. Not the most elegant approach, tho.

**Comment by delphinian** [comment]
did the trick. duplicate options were the cause.
