### ISSUE TITLE
API Call to get all Orders

### ISSUE THREAD

**Issue by frankmaina** [Shopify/shopify_python_api#167]
Hi, whats the exact API call to get all orders even closed and archived ones?

Shopify.Order.find(status='any') only returns a limed number

**Comment by jamiemtdwyer** [comment]
Can you try `Shopify.Order.find({'status': 'any'})`? I believe this is the correct syntax here.

**Comment by frankmaina** [comment]
Hi, that threw a ResourceNotFound error. All my calls are limiting the orders to 50 yet i have close to 1000 errors but a bulk of them are archived.

**Comment by frankmaina** [comment]
The issue was pagination, but thanks for your support
