### ISSUE TITLE
Unable to get access token uing session.request token

### ISSUE THREAD

**Issue by akhayoon** [Shopify/shopify_python_api#171]
I've been trying to use this method to get the access token

token = session.request_token(params)

but I keep getting this hmac validation error:
 ValidationException('Invalid HMAC: Possibly malicious login')

It's strange because when I make the call using the /oauth url via postman providing the (client_id, client_secret and code) the call works and return the access_token

What I don't understand is why the request_token method doesn't work anymore? (I used this library about 3 years ago and it worked fine)

I'm using the latest version that doesn't use signatures anymore.

**Comment by austenc** [comment]
@akhayoon Were you ever able to figure this out?

**Comment by akhayoon** [comment]
@austenc I wish buddy, still just doing it manually. Let me know if you want the code to do that as a quick workaround.

**Comment by ubaydinoyatov** [comment]
@akhayoon I have the same error

**Comment by gautham20** [comment]
I got it to work,
Make sure the session object is set up with api_key and secret key.

should be in the lines of,

shopify_session = shopify.Session(shop, token=kwargs.get('token'))
        shopify_session.setup(api_key = consts.SHOPIFY_APP_API_KEY,
                secret= consts.SHOPIFY_APP_API_SECRET)
        shopify_session.request_token(params)

**Comment by victor-guoyu** [comment]
I'm having the same error, tried to setup the session with `api_key` and `secret`, got no luck. :(

Does this project still being maintained by Shopify?

**Comment by jamiemtdwyer** [comment]
Not able to replicate on my end.

Here's an example implementation using Flask that should help to better understand the authentication flow. 

https://gist.github.com/jamiemtdwyer/b6c8af90277869fe899c130ddf0ffcb9
