### ISSUE TITLE
Add Support for Storefront Access Token

### ISSUE THREAD

**Issue by pbojinov** [Shopify/shopify_python_api#185]
Add support for creating, getting and deleting Storefront Access Tokens.

**Comment by Sanjeev-Gupta** [comment]
Hi,

For public app, I am getting null when calling storefront api of access token. Can anyone tell me how will i create access token for storefront for public app.

**Comment by jamiemtdwyer** [comment]
Closed by https://github.com/Shopify/shopify_python_api/pull/227
