### ISSUE TITLE
shopify.RecurringApplicationCharge.cancel() AttributeError: 'function' object has no attribute 'body'

### ISSUE THREAD

**Issue by coler-j** [Shopify/shopify_python_api#190]
I see [this issue](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/shopify-python-api-cancelling-order-is-broken-391204) about cancelling orders, I am getting the same behavior when trying to cancel RecurringApplicationCharges.

I get 'AttributeError: 'function' object has no attribute 'body''

I have tried:
`user_current_charge = shopify.RecurringApplicationCharge.current()`

then:
`shopify.RecurringApplicationCharge.cancel(user_current_charge)`

Is this not how it is supposed to work?

**Comment by nivcaner** [comment]
this is happening to me as well.

**Comment by SolveCore-Inc** [comment]
Is this repo not maintained by Shopify?

**Comment by jamiemtdwyer** [comment]
This repo is maintained by Shopify, apologies that we haven't had the
cycles to look into this issue yet.

I'll try to take a crack at this in the next week or two - is anyone able
to provide a backtrace?

FWIW, only one recurring charge can be active at a time, so creating a new
charge will automatically destroy the old one.

**Comment by SolveCore-Inc** [comment]
-- Please reply above this line --


Hello Shopify/shopify_python_api,

We have received your email request! Someone from our team will get
back to you as soon as possible. We will usually respond within 1-2
days, however, if this is an emergency we will respond sooner.

Thank you for your patience!

**Comment by rnovacek** [comment]
Part of backtrace after calling `charge.cancel()` is like this:
```
  File "/app/.heroku/python/lib/python3.6/site-packages/shopify/resources/recurring_application_charge.py", line 28, in cancel
    self._load_attributes_from_response(self.destroy)
  File "/app/.heroku/python/lib/python3.6/site-packages/shopify/base.py", line 133, in _load_attributes_from_response
    if response.body.strip():
AttributeError: 'function' object has no attribute 'body'
```
It looks like the problem is this:
```self._load_attributes_from_response(self.destroy)```
`self.destroy` is a function but `_load_attributes_from_response` expects a response. The `destroy` function doesn't even return a response. Maybe just calling `self.destroy()` would be enough here.

**Comment by jamiemtdwyer** [comment]
As the previous commenters have said, cancelling a RecurringApplicationCharge in the Shopify API doesn't return a body.

The `cancel()` method should just be removed entirely, and the `destroy()` method should be used in its place.

e.g.

```python

>>> charge = shopify.RecurringApplicationCharge.current()
>>> charge.destroy()
>>> shopify.RecurringApplicationCharge.current() == None
True
```
