### ISSUE TITLE
Add Support for Product Listing API

### ISSUE THREAD

**Issue by pbojinov** [Shopify/shopify_python_api#192]
Not sure if this is currently possible with this package, I couldn't find any mention anywhere in the code.

https://help.shopify.com/api/reference/productlisting

**Comment by jamiemtdwyer** [comment]
I'm planning to add support for ProductListing and CollectionListing sometime next week when I return to work (currently at Shopify Unite). If someone wants to beat me to it and throw up a PR, I should be able to find time this week to review and merge.

**Comment by wowkin2** [comment]
@jamiemtdwyer is there any success with that (`Product Listing API`)?

**Comment by jamiemtdwyer** [comment]
Closed by https://github.com/Shopify/shopify_python_api/pull/222.
