### ISSUE TITLE
Price Rules API

### ISSUE THREAD

**Issue by allanarmstrong** [Shopify/shopify_python_api#196]
From my understanding the Discount API is going to be deprecated and replaced with the [Price Rules API](https://help.shopify.com/api/price-rules). Will this be added the python api in the future? I've implemented it myself and was wondering if it was worth making a pull request (with passing tests and everything!) but if it's a planned feature in a future version then I might as well just wait. While reading the CONTRIBUTING.md file I noticed it didn't say anything about pull requests so was unsure if they were welcome. 

Thanks

**Comment by jamiemtdwyer** [comment]
Hey Allan,

PRs are definitely welcome! If you want to commit what you have so far,
that would be a great start. I would be happy to review and write any
remaining tests.

**Comment by allanarmstrong** [comment]
Thanks @jamiemtdwyer. Made a pull request #197

**Comment by jamiemtdwyer** [comment]
It's live! Thanks again @allanarmstrong for your contribution. 💪
