### ISSUE TITLE
Add a customer

### ISSUE THREAD

**Issue by lyrubiano5** [Shopify/shopify_python_api#200]
I am trying to create a new customer with the next code:
new_customer = shopify.Customer()
    new_customer.first_name = "andres"
    new_customer.last_name = "lara"
    new_customer.company = "my_company"
    success = new_customer.save()

But the api haven't "company"

**Comment by iaserrat** [comment]
I wasn't able to replicate. Are you using the latest version? Did you give `write` permissions to your API keys in the Shopify Admin?

**Comment by iaserrat** [comment]
Also, the `company` field belongs to the nested `Address` object not the customer directly.

https://help.shopify.com/api/reference/customer
