### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vivaelnino9** [Shopify/shopify_python_api#201]
Hi!

I have a private app set up with shopify and I'm trying to make a Django app that uses the Shopify Python API however I can't seem to get passed step 6 in the Getting Started instructions!

``` python
shop_url = "https://%s:%s@SHOP_NAME.myshopify.com/admin" % (API_KEY, PASSWORD)
shopify.ShopifyResource.set_site(shop_url)
shop = shopify.Shop.current()
```

Above is all I have put in, obviously with my shop name and api credentials filled in, however when it gets to that last line I get an SSL error:

``` python
pyactiveresource.connection.Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

I have a decent understanding of what the error is but I don't understand why I'm getting it when I know for a fact I'm using the right credentials and following the instructions properly.

Anyone have an ideas?

**Comment by johnsliao** [comment]
I've also seen this issue. Does anyone know how to resolve?

**Comment by clintonb** [comment]
I have the same issue on macOS with Python 3.6.0. This solution—detailed at https://stackoverflow.com/a/42098127/592820—resolved the problem for me:

Run `/Applications/Python\ 3.6/Install\ Certificates.command` from a terminal.

**Comment by jamiemtdwyer** [comment]
If you're having issues with Python and SSL, you can either follow the steps above provided by @clintonb (thanks!) or install the [certifi](https://pypi.python.org/pypi/certifi) package.

**Comment by KevinMind** [comment]
@clintonb You da bomb! I also had no problems with 2.7 but, when switched to 3.6 your fix worked.

**Comment by raminpapo** [comment]
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import shopify

**Comment by b34nb0** [comment]
Was having this same issue running python 3.9 on a conda virtual environment. Installing the `certifi` package didn't do it for me (since I had it already installed), I was able however to solve it with this: [https://stackoverflow.com/a/77491061/20258560](https://stackoverflow.com/a/77491061/20258560)
