### ISSUE TITLE
How do you use the product_search_engine.py?

### ISSUE THREAD

**Issue by coler-j** [Shopify/shopify_python_api#206]
There are no tests for it, and no documentation, searching on the web turns up no results either. Any ideas?

**Comment by jamiemtdwyer** [comment]
Any ideas @kevinhughes27

**Comment by kevinhughes27** [comment]
I don't believe we have a resource for that (looking at our official api docs). This might be a leftover file from long ago.

**Comment by kevinhughes27** [comment]
@jamiemtdwyer we should remove that file as well.

**Comment by jamiemtdwyer** [comment]
You're right, shouldn't have closed this prematurely. Will action this and close again.
