### ISSUE TITLE
Customer search appears to be broken. 

### ISSUE THREAD

**Issue by halfnibble** [Shopify/shopify_python_api#210]
If I run the following:
`shopify.Customer.find(email='customer@gmail.com')`

The response always seems to be the first 50 customers, which may or may not include the customer with the above email.

**Comment by halfnibble** [comment]
Ok, after looking through the source code, it came to me.
There is a search method I was not aware of:

This works:
`shopify.Customer.search(query='email:customer@gmail.com')`

**Comment by wowkin2** [comment]
I also tried `shopify.Customer.find(email='email:customer@gmail.com')` but it didn't work for me too.
Thanks for the hint.

I think this also should be added to [Documentation #132 ](https://github.com/Shopify/shopify_python_api/issues/132)

**Comment by tanner-ducharme** [comment]
This is probably due to my python inexperience, but how would you use the above method when the email is stored in a variable. I tried
`shopify.Customer.search(query='email:my_email')`

but that's returning an empty list
also it works when I hardcode the email like in the example above. How do I correctly GET the customer? Thanks

**Comment by halfnibble** [comment]
Try this:
`shopify.Customer.search(query='email:{0}'.format(my_email))`

**Comment by coler-j** [comment]
Is there an equivalent search method for Orders?

**Comment by jamiemtdwyer** [comment]
The [Order API](https://help.shopify.com/en/api/reference/orders/order) doesn't provide a search endpoint, unfortunately.

**Comment by coler-j** [comment]
Hmm, from these two posts, I _think_ that I might have it working: 

- https://github.com/Shopify/shopify_python_api/issues/249#issuecomment-393145174)
- https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/would-the-values-for-order_number-and-name-always-be-the-same-in-order-api-258539

```
from shopify import Order


class ShopifyOrder(Order):
    @classmethod
    def lookup(cls, order_name):
        """
        Patched Shopify Order resource to allow lookup by order name.
        """
        
        order_lookup = urllib.parse.urlencode({'name': order_name, 'status': 'any'})
        path = '/admin/orders.json?{order_lookup}'.format(order_lookup=order_lookup)
        resources = cls._build_list(cls.connection.get(path, cls.headers))
        if resources:
            return resources[0]
        else:
            return None
```

**Comment by coler-j** [comment]
@jamiemtdwyer do you forsee any issue with that method?

**Comment by jamiemtdwyer** [comment]
If you're just interested in finding orders by `name`, I think that should already be supported... let me play around in the console a bit and report back

**Comment by jamiemtdwyer** [comment]
both `find() `and `find_first()` accept **kwargs ([source](https://github.com/Shopify/pyactiveresource/blob/84c19d9918cc0589c85af47285968bba3f8bf865/pyactiveresource/activeresource.py#L366-L404)), so you can send any additional parameters simply as arguments

```
>>> shopify.Order.find(name=1484)
[order(597907439638)]
>>> shopify.Order.find_first(name=1484)
order(597907439638)
```

^ I sanity checked this result on my shop, and it does return the expected order.

Keep in mind that `find()` will always return a `list`, where `find_first()` will always return the first element of the list. IIRC searching by order name is a bit fuzzy, so `find_first()` might not always return the expected result, it might be better to use `find()` and compare the results with the expected order name.

Hope this helps @coler-j! Let me know if anything is unclear.

**Comment by jamiemtdwyer** [comment]
Here's an example that includes `status` as well, if that's helpful:

```
>>> shopify.Order.find_first(name=1484, status='closed')
>>> shopify.Order.find_first(name=1484, status='open')
order(597907439638)
```
