### ISSUE TITLE
How to make products/variants Search using this API?

### ISSUE THREAD

**Issue by wowkin2** [Shopify/shopify_python_api#219]
I couldn't find an class or example how to perform Search through API.
The only option I found (here on [Stackoverflow](https://stackoverflow.com/questions/14326640/shopify-is-it-possible-to-find-a-product-by-sku-number)) is to query URL like following:
`/admin/products/search.json?query=sku:abc123`

Is it planned to add this functionality?

**Comment by jamiemtdwyer** [comment]
That StackOverflow post is out of date. The products resource hasn't supported the `search` endpoint in quite some time.

There are some filters you can apply to the index endpoint as described [here](https://help.shopify.com/api/reference/product#index), but if you're looking to search by particular properties (i.e. `sku`), you'll need to implement this within your application by indexing the records and searching locally.
