### ISSUE TITLE
SSL verify failed (developing with localhost)

### ISSUE THREAD

**Issue by KevinMind** [Shopify/shopify_python_api#232]
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

Am I supposed to be setting up an ssl for localhost to test shopify api?
The app is deployed and works on my remote server, but now when I try to run it locally, I always get this error when trying to read the oauth callback url.

Error triggers here.

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py in do_open, line 1320
--

I know the api is using urllib.reqeusts to handle the token exchange, so is this call expecting my server to be running behind an ssl, or am I missing something?

**Comment by wowkin2** [comment]
You can use [ngrok](https://ngrok.com/) to create public url to your local machine.
