### ISSUE TITLE
Batch update multiple items

### ISSUE THREAD

**Issue by wowkin2** [Shopify/shopify_python_api#234]
Is there any possibility to do a batch update for multiple items (e.g. Variants)?
Something like:
``` python
shopify.Variant.update_many({"price": 100}, [variant_id1, variant_id2, variant_id3])

**Comment by clintonb** [comment]
You can update multiple variants of the same parent product. To my knowledge, there is no API endpoint that supports multiple variants of differing products. See https://help.shopify.com/api/reference/product#update.

**Comment by wowkin2** [comment]
How the batch update work in Shopify Admin panel?
Is it sending multiple requests too?

**Comment by jamiemtdwyer** [comment]
Yup, and if you queue up enough updates you will notice they are backgrounded and don't complete immediately.

Some of the mutations in the [GraphQL API](https://help.shopify.com/en/api/graphql-admin-api) support bulk operations, if that interests you.

Closing this as there's no way to support this in the package.
