### ISSUE TITLE
saving asset error - liquid contains illegal characters

### ISSUE THREAD

**Issue by embedded1** [Shopify/shopify_python_api#236]
I'm trying to save a backup of the product-template.liquid file and this is the code I'm using:
```

    asset = shopify.Asset({'theme_id': main_theme_id})

    asset.key = asset_path #the backup liquid

    asset.source_key = source_key #asset.source_key of product.liquid

    asset.save()
```

and this is the error message returned: 

> [u'"sections/product-template.bak.liquid" contains illegal characters']

Does anyone know what went wrong and how to solve this issue?

Thanks

**Comment by nwtn** [comment]
This appears to be the expected behaviour when there is a problem with the Liquid file. Feel free to reopen if the Liquid file does _not_ actually contain any illegal characters.
