### ISSUE TITLE
Adding snippet to liquid returns Liquid syntax error (line 1): Unknown tag ''" 

### ISSUE THREAD

**Issue by embedded1** [Shopify/shopify_python_api#237]
I'm trying to add our snippet to the product-template.liquid by using BeautifulSoup to search and edit the liquid file.

Then, I trying to save the asset by setting `asset.value = str(soup)`

Saving the asset, returns this error:

>  Liquid syntax error (line 1): Unknown tag ''" 

Does anyone know how to save the change after the snippet has been added?

Thanks

**Comment by nwtn** [comment]
Closing because this seems like an issue with BeatifulSoup or whatever else you’re easing to edit the liquid, not with this library
