### ISSUE TITLE
Timeline on adding multi-location inventory?

### ISSUE THREAD

**Issue by nodeit** [Shopify/shopify_python_api#238]
As you've probably heard, Shopify is changing the way inventory is managed through the API

https://help.shopify.com/api/tutorials/inventory-migration-guide?utm_source=exacttarget&utm_medium=email&utm_campaign=multilocation1#comparison-api-requests-in-http

Do you plan on updating this module and if so do you have an ETA?

**Comment by jamiemtdwyer** [comment]
Hey @nodeit,

I plan on keeping this package at parity with [`shopify_api`](https://github.com/shopify/shopify_api) for as long as I have the means to support it. As soon as it gets added to `shopify_api`, I'll start the task of porting over the new code to this package.

Cheers!

**Comment by nodeit** [comment]
@jamiemtdwyer Sounds great; thanks for the info!
