### ISSUE TITLE
Any plans for Async API?

### ISSUE THREAD

**Issue by wowkin2** [Shopify/shopify_python_api#242]
Hi, is there any plans how and when to implement async API?
Perhaps, somebody has the alternative library that supports async?

If there is any vision or plan - I can help to implement it.

**Comment by nwtn** [comment]
This is on our backlog of features to consider, but we don’t currently have any firm plans for it on our roadmap.

**Comment by jaddison** [comment]
@wowkin2 I have recently found https://github.com/osiset/basic_shopify_api.
