### ISSUE TITLE
Single API Call to Update Variant Price

### ISSUE THREAD

**Issue by i14g** [Shopify/shopify_python_api#247]
I need to update a ton of variants. Maybe I'm misunderstanding, but it seems that Variant.find() makes a call and is really slowing down the update by half. I've stored the variant ids so I can access them very easily, but is there a way to avoid this call? 
`variant = shopify.Variant.find(variant_id)`
 `variant.price = item_price`
 `variant.save()`

**Comment by jamiemtdwyer** [comment]
Correct, find() is always going to make a remote request to fetch the resource.

To get around this, you can do something like 

```
variant = shopify.Variant()
variant.id = 12345 # id you have in db
variant.price = 9.99
variant.save()
```

**Comment by i14g** [comment]
Thanks Jamie!
