### ISSUE TITLE
What exactly does asynchronous mean?

### ISSUE THREAD

**Issue by tanner-ducharme** [Shopify/shopify_python_api#258]
I'm new to APIs. I was wondering exactly what is meant by the  lack of support for asynchronous requests?

**Comment by nwtn** [comment]
Synchronous requests block the execution of code. The code will wait for a response before continuing.

Asynchronous requests do not block execution of code by waiting for a response. Execution continues, a response can happen at any time, and when it does a callback function gets executed.
