### ISSUE TITLE
Releases - been stuck in 3.1.0

### ISSUE THREAD

**Issue by joantune** [Shopify/shopify_python_api#282]
Hi everyone!

Is this library still supported? I see evolving changes like adding the calculate refund on the `shopify.Refund` but I have seen no releases since May this year - is there another release expected? is there a way I can get my hands to some sort of development version? 
thanks!

**Comment by jamiemtdwyer** [comment]
> is there a way I can get my hands to some sort of development version?

You sure can. You can use pip's [VCS Support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) to point to a git branch or tag.

I'm planning on releasing a new version within the next few days, or sometime next week at the latest. Thanks for your interest!

**Comment by joantune** [comment]
Thanks for the tip @jamiemtdwyer! I have been only pythoning for 3 months now.

**Comment by jamiemtdwyer** [comment]
No worries. I'll leave this issue open until it's closed out by the next release.

**Comment by dave4jr** [comment]
@jamiemtdwyer Thanks Jamie, I left an issue, https://github.com/Shopify/shopify_python_api/issues/275, regarding account activation link. Anyway this could be included in the latest release or no?  Thanks!

**Comment by kwasielew** [comment]
Hey, 
How is release going on?
Additionally I don't want to create new issue/question, so I will ask here - is this python API supports:
- endpoints from https://help.shopify.com/en/api/reference/inventory/location ? E.g I want simply to get all locations

Thanks

**Comment by jamiemtdwyer** [comment]
Hey all,

Sorry for the delay. I was away on vacation last week. Version 4.0.0 is now available on [pypi](https://pypi.org/project/ShopifyAPI/).

@kwasielew, the library does support the Location resource. You can retrieve all locations for shop by authenticating to the shop, and then calling `shopify.Locations.find()`.
