### ISSUE TITLE
Updating a Fulfillment via API Wrapper Fails

### ISSUE THREAD

**Issue by andessen** [Shopify/shopify_python_api#310]
I have been fully utilizing the Python API Wrapper with general success but now I have determined a potential bug when trying to make a PUT request via the API via the fulfillments endpoint.

>>> sff = shopify.Fulfillment.find_first(order_id='932467572816')
>>> ssf.tracking_url = 'http://helloworldtracking.com/some_id'
>>> ssf.save()
>>> ssf.tracking_url
>>>

Here the tracking url is being updated but fails to change via the wrapper. Attempting the same request via a PUT utilizing the endpoint via requests seems to achieve the desired result.

Question: Am I utilizing the API appropriately for fulfillments & PUTs or this is a bug?

https://github.com/Shopify/shopify_python_api

**Comment by leocxy** [comment]
Hi 

I got the same issue. 

Here are my configs

API Version: 2020-07
ShopifyAPI: 8.0.4

Below is my codes

`
fulfills = self.api.Fulfillment.find(order_id=order_id)
            for fulfill in fulfills:
                # check tracking number
                if len(fulfill.tracking_number) == 52 and not fulfill.tracking_url:
                    tracking_url = 'https://www.nzcouriers.co.nz/nzc/servlet/ITNG_TAndTServlet?page=1&VCCA=Enabled&Key_Type=BarCode&barcode_data={}'
                    tracking_url = tracking_url.format(fulfill.tracking_number.replace(' ', '+'))
                    print(tracking_url)
                    fulfill.tracking_url = tracking_url
                    res = fulfill.save()
                    print(res, fulfill.errors.full_messages())
                    exit()
`

The res showing True, and none error messages. But the tracking URL does not update...

**Comment by mllemango** [comment]
Hey @leocxy, in order to update the the tracking_url of the fulfillment, you actually have to use `fulfill.tracking_urls` by assigning a list to it, eg. ` fulfill.tracking_urls = ["google.com"]`. 
Unfortunately this isn't super clear, and I only found this out by looking at our [API documentation](https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#update_tracking-2020-01).
Let me know if you're still running into issues updating tracking!

**Comment by leocxy** [comment]
Hi @mllemango, I was using GraphQL instead of "ShopifyAPI" to updating the tracking info. 

I know the API documentation. But I don't know how to call that with the python package "ShopifyAPI". 

Anyway, thank you for your reply.
