### ISSUE TITLE
Retrieving Pageviews, Sessions through API

### ISSUE THREAD

**Issue by lowercase00** [Shopify/shopify_python_api#315]
Documentation says it only works via ShopifyQL.
Is there anyway to send get requests to endpoint reads ShopifyQL?
If not, where should I input queries?
Thanks

**Comment by nwtn** [comment]
This gem only supports the Admin API, not the Analytics API. For support on that API, please post in our [APIs and SDKs Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology)
