### ISSUE TITLE
how to list existing webhooks and delete them? / more Python API docs?

### ISSUE THREAD

**Issue by eliot1785** [Shopify/shopify_python_api#316]
Hi, I've just started with the Shopify API and I am pretty lost... sorry in advance that this question is so basic, but I can't really find instructions for basic-to-intermediate stuff (the kind of stuff that might come after the README for this GitHub repo) in the docs. So I could use a pointer on what to read.

For example I have created a few webhooks like the following and it works (I was basing this on somebody else's code that I found)

```
session = shopify.Session(shop, token)
shopify.ShopifyResource.activate_session(session)

new_webhook = shopify.Webhook()
new_webhook.address = mydomain + "/shopify/" + str(shop_id) + "/" + event
new_webhook.format = 'json'
new_webhook.topic = event
success = new_webhook.save()
```

But now I would like to list the existing webhooks and delete them, and I don't know where to look in the docs to find instructions for that. Also, if save() doesn't work, I'd like to see the error message for that but I can't figure out how.

More generally, I found the README on the main GitHub page (https://github.com/Shopify/shopify_python_api) to be helpful. What should I read after that to understand further how to use the Python API? When I go to the Shopify Docs page, I can find a lot of information on the REST API itself, but nothing on how to interact with it using the Python API.

In sum, where's the rest of the Python API documentation?

**Comment by eliot1785** [comment]
I was able to find Webhook documentation for the REST API here, it's just a bit hidden under Events: https://help.shopify.com/en/api/reference/events/webhook

I think we are just going to use the raw webhooks instead of the Python API (partly because it's better-documented) so I'm going to close this.

**Comment by sillycube** [comment]
I tried to use Rest API https://mystore.myshopify.com/admin/api/2020-10/webhooks.json and I could see that there was a webhook. When I tried https://mystore.myshopify.com/admin/api/2020-10/webhooks/count.json, it also showed 1.

However, when I tried to use Shopify.Webhook.count(). It only shows 0. 

When I tried shopify.Product.count(), it was showing 260 which is correct as the Rest API. I think the webhook python API is not working here.

**Comment by mllemango** [comment]
Hey @sillycube, you've detected an interesting behaviour of webhooks themselves. 
Webhook subscriptions are generally scoped to an app, and then can be accessed by the app itself, but subscriptions created via the shop admin (which I assume is what you did since it works in browser) is actually an exception. Those webhooks are associated solely to the shop so the API actually can't access them. 
In order to use the python api, I suggest you create the webhook subscriptions through the library as well. Then you'll be able to use `shopify.Product.count()`
```
body = {
    "topic": "orders/create",
    "address": "https://whatever.hostname.com/",
    "format": "json"
 }
 shopify.Webhook.create(body)
```

**Comment by sillycube** [comment]
Thanks, Melanie. You're right. I created a webhook in the admin portal for testing. After testing for a while, I realized these are 2 different numbers. Thanks for your code. I'll try it soon!
