### ISSUE TITLE
Can't return order as a json object

### ISSUE THREAD

**Issue by ckissi** [Shopify/shopify_python_api#326]
I want to read order from API and simply return it as a JSON object:

```
order = shopify.Order.find(orderid)
return jsonify(json.dumps(order))
```

**I get this:** TypeError: Object of type Order is not JSON serializable

I've tried to serialize just line_items with this code:
```
order = shopify.Order.find(orderid)
return jsonify(json.dumps([ob.__dict__ for ob in order.line_items]))
```
**I get this:** TypeError: Object of type ShopifyResourceMeta is not JSON serializable

**Comment by hicham99** [comment]
order is an instance of the Order class . You can get the request results as json just by adding .tojson()
`order = shopify.Order.find(orderid).tojson()`

**Comment by troyshu** [comment]
@hicham99 I'm getting `AttributeError: tojson`. `to_json()` does return a JSON string though.

Another solution to get an Order (or any other object) as a dictionary @ckissi is to use python's built in `__dict__` attribute. For example, `order.__dict__['attributes']` gives is a dictionary of all of Order's attributes.

**Comment by akhtariali** [comment]
The problem w/ `Model.attributes` is that it isn't recursive. When passing `Order.attributes` in response, for example, I get `Object of type CurrentSubtotalPriceSet is not JSON serializable` from Django.

`json.loads(order.to_json())`

This is the only way I could find to convert an `Order` to a JSON serializable dict. But it's clearly dirty.
