### ISSUE TITLE
Implement relative cursor pagination

### ISSUE THREAD

**Issue by GhostApps** [Shopify/shopify_python_api#337]
This really needs to be implemented as its now in the official API, I saw there is a branch that has been started but can we get an ETA on when it will be done?

**Comment by tanema** [comment]
We have peopl working on the right now however I do not have an ETA for you. I will update this issue when we are closer to releasing it.

**Comment by emdemir** [comment]
Any update on this yet? From what I can see `pyactiveresource.ActiveResource._find_every` will directly process the body of the response while throwing away the header data. I can try to send in a PR where it keeps the headers and `next()` and `previous()` methods can be added to an `ActiveResource` where the `Link` header field is used.

**Comment by emdemir** [comment]
Check out #338.

**Comment by tanema** [comment]
Thanks @emdemir for all your work, I have merged the changes to allow cursor pagination in https://github.com/Shopify/shopify_python_api/pull/352
