### ISSUE TITLE
Shopify Refund doesnt follow the ActiveResource structure

### ISSUE THREAD

**Issue by adadkins** [Shopify/shopify_python_api#342]
The flow for a shopify refund is get Order line items, then call Refund Calculate at:

orders/#{order_id}/refunds/calculate.json

Once you have that response, put that response in the body and call:

orders/#{order_id}/refunds.json

However, I dont see anyway to make this call with how this project is currently structured. It looks like active resource requires a Class name (refund) and then a method name. However this end point doesnt have a method name.

**Comment by kylebjordahl** [comment]
For anyone that stumbles across this, I had to create a refund like this: 

```py
calculated = shopify.Refund.calculate(shopify_order_id, refund_line_items=refund_line_items)
# ...process calculated result, make refund_dict
refund = shopify.Refund(refund_dict, prefix_options={'order_id': shopify_order_id})
```
