### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by GhostApps** [Shopify/shopify_python_api#346]
Once again I have received an email from Shopify telling me that I am using an old version of the API and when I come to check on progress on cursor pagination there isn't any.
Pull requests have been open for weeks, I would expect Shopify to keep this package in line with [the Ruby one](https://github.com/Shopify/shopify_app) or a warning that it is not regularly updated.

**Comment by hgolov** [comment]
Ditto. What's happening?

**Comment by tanema** [comment]
No, it is not, this repo will receive support soon and I am sorry for the state of it currently. We have a bit of a crunch on right now, after that our libraries will receive more attention
