### ISSUE TITLE
API version 2019-10 fails with variant updates

### ISSUE THREAD

**Issue by blconn** [Shopify/shopify_python_api#347]
Hello,

I've found what I believe is a bug with the current version of the project (5.1.2).  Targeting API version 2019-10 with Shopify, a call to update the price of a product variant fails with a 400 Bad Request error.  The complete text of the error follows:

pyactiveresource.connection.BadRequest: Response(code=400, body="b'{"error":"Write requests to inventory_quantity and inventory_quantity_adjustment are no longer supported. Please use the Inventory Levels API."}

Steps to reproduce:

1. Create connection via private app key targeting API version 2019-10 (admin/api/2019-10)
2. Set shop resource
3. Set a new object as a product
4. From the product, set another new object as a product variant
5. Call <variant>.price = float(<price>)   (Running print(<variant>.price) does return the updated price here)
6. Call <variant>.save()

Upon calling save(), the above error is thrown.

After reviewing documentation, it appears that inventory_quantity should be removed from the list of variant attributes as it is fully deprecated in API version 2019-10.  This call works without issue targeting API version 2019-07.

**Comment by tanema** [comment]
Thanks for the thorough report, we will hopefully have someone fix this soon.

**Comment by jamiemtdwyer** [comment]
@blconn, this workaround is working for me:

```
>>> v = shopify.Variant.find(limit=1)[0]
>>> del v.attributes['inventory_quantity']
>>> del v.attributes['old_inventory_quantity']
>>> v.save()
True
```

**Comment by blconn** [comment]
Very nice - thank you!  Just to clarify - do you remove the attributes
every time you make the call?

**Comment by jamiemtdwyer** [comment]
Hey @blconn - yes, every time you fetch a variant from Shopify, you'll need to delete these keys before saving. Hope this helps.

**Comment by blconn** [comment]
Hi there - I was able to confirm this workaround fixed the issues we had
with product variant attribute adjustments and we are now fully integrated
into API 2019-10.  Thanks very much for the tip - this was a huge help for
us!
