### ISSUE TITLE
Problems while validating HMAC

### ISSUE THREAD

**Issue by lowercase00** [Shopify/shopify_python_api#351]
Hey all.
I'm trying to validate HMAC without success. The readme says "Ensure the provided hmac is valid. The hmac is signed by Shopify as explained below, in the Verification section.", but does not provide a "verification section". Edit: It seems this comes from the Help Center that gives an example in Ruby. On that example they say something like `secret = 'hush'`, but I did not understand where this comes from.

Here's my code so far, the main route is the redirect route after an user installs the app.

```
@main.route('/')
def index():
    api_secret = b'jfdklsjfkadskjlfads'

    # Get params
    code = request.args.get('code')    
    myhmac = request.args.get('hmac')
    shop = request.args.get('shop')
    state = request.args.get('state')
    timestamp = request.args.get('timestamp')
    
    # Generate "clean" parameters (without HMAC)
    clean = "code=" + code + "&" + "shop=" + shop + "&" + "state=" + state + "&" + "timestamp=" + timestamp
    clean = clean.encode('utf-8')
    myhmac = myhmac.encode('utf-8')

    # Compare HMAC
    # I'm guessing this is where things go wrong. I've tried with the api_secret (from the partners app API Keys), state, etc. But I don't know which "secret" should I put in here.
    digest = hmac.new(clean, api_secret, hashlib.sha256).digest()
    computed_hmac = base64.b64encode(digest)
    result = hmac.compare_digest(computed_hmac, myhmac)

    comparison_test = { "result": result }

    return jsonify(comparison_test)
```

Even though I don't get an error, it returns `false`. This is an app I created in Shopify Partners, with a developers store (with the developer view option enabled).

Any ideas on what I might be doing wrong?

**Comment by tanema** [comment]
There might be a few things that are going
- Your api_secret maybe needs a u prefix instead of b
- You might be missing a parameter when you rebuild the params

I checked the oauth docs and it doesnt seem like the example encodes the digest https://help.shopify.com/en/api/getting-started/authentication/oauth#verification

Can you point me toward the help center docs you are looking at so I can get a better idea of what you are working off of? 

Comparing HMACs is a finicky task across languages to get all the encodings right so it normally takes some fiddling. I will see if I can try and get a working example in my test django app

**Comment by tanema** [comment]
This is how I got it to work in my own app 

```
api_secret = apps.get_app_config('shopify_app').SHOPIFY_API_SECRET
params = request.GET.dict()
myhmac = params.pop('hmac')
line = '&'.join([
    '%s=%s' % (key, value)
    for key, value in sorted(params.items())
])
h = hmac.new(api_secret.encode('utf-8'), line.encode('utf-8'), hashlib.sha256)
if hmac.compare_digest(h.hexdigest(), myhmac) == False:
    messages.error(request, "Could not verify a secure login")
    return redirect(reverse(login))
```

**Comment by tanema** [comment]
Here I added state checking and Hmac validation to my example app https://github.com/Shopify/shopify_django_app/blob/master/shopify_app/views.py

**Comment by lowercase00** [comment]
That's perfect mate, I got it working with you example.
I encoded the digest sice that's the way it's done in the HMAC Webhook validation, but indeed, documentation does not mention it.
Anyways, problem solves, thanks a lot!! I'll take a look at your app to see how you structured your code.
Cheers!

**Comment by tanema** [comment]
I believe that encoding in webhook validation has something to do with the fact that you are validating a POST body instead of GET query params. Base64 makes the hmac safe for serialization

**Comment by sashahilton00** [comment]
For anyone else who stumbles across this issue, I encountered problems when trying to validate bulk action requests, namely where multiple `ids` were being passed. The existing logic in the library appears to split an original parameter of `ids[]=123456` into a string array of `["1", "2", "3", "4", "5", "6"]`. I have thus tweaked the line that handles the decoding of arrays/lists to use the inbuilt `getlist()` method of `MultiDict`, which works fine. A code sample is included below, as much for my benefit as everyone else's. I am using flask currently, so syntax may differ for your app.

```python
import six, json, hmac, hashlib

def encode_query_pairs(params):
    """
    Sort and combine query parameters into a single string, excluding those that should be removed and joining with '&'
    """

    def encoded_pairs(params):
        for k, v in six.iteritems(params):
            if k == 'hmac':
                continue

            if k.endswith('[]'):
                # foo[]=1&foo[]=2 has to be transformed as foo=["1", "2"] note the whitespace after comma
                v = json.dumps(params.getlist(k))
                k = k.rstrip('[]')

            # escape delimiters to avoid tampering
            k = str(k).replace("%", "%25").replace("=", "%3D")
            v = str(v).replace("%", "%25")
            yield '{0}={1}'.format(k, v).replace("&", "%26")

    return "&".join(sorted(encoded_pairs(params)))

def check_hmac(params):
    api_secret = current_app.config.get('SHOPIFY_SHARED_SECRET')
    actual_hmac = request.args.get('hmac')
    sorted_query = encode_query_pairs(params)

    calculated_hmac = hmac.new(api_secret.encode('utf-8'), sorted_query.encode('utf-8'), hashlib.sha256).hexdigest()

    return hmac.compare_digest(calculated_hmac, actual_hmac)

hmac_valid = check_hmac(request.args)
```

**Comment by tipu002** [comment]
You can try
https://medium.com/@BorhanTipu/django-shopify-webhook-hmac-verify-bf6f23e992c1
