### ISSUE TITLE
ShopifyResource.find does not propagate kwargs to PaginatedCollection

### ISSUE THREAD

**Issue by Philpax** [Shopify/shopify_python_api#356]
Hey folks, I'm testing the new pagination and I've found that `resource.find(no_iter_next=True)`
doesn't work as expected (e.g. the resulting iterator will still fetch additional pages).

After having a quick look through the source code, it appears that this is because the `kwargs` are never passed through: https://github.com/Shopify/shopify_python_api/blob/master/shopify/base.py#L213

Overriding the variable on the collection works fine, but is non-ideal:
```python
        collection = resource.find(**kwargs)
        collection._no_iter_next = True
```

**Comment by tanema** [comment]
Hey @Philpax thanks for the suggestion, I will take a look at this.

**Comment by GhostApps** [comment]
Thought I was going mad, couldn't figure out why shopify.Order.find(limit=5) would still return all of the orders but I guess this explains it

**Comment by GhostApps** [comment]
It's worse than that, if you do 
```
orders = shopify.Order.find(limit=5)
print(len(orders))
for order in orders:
    print(order)
print(len(orders))
```
The length of orders is 5 but once the for loop runs it is the total amount of orders in the shop i.e. 100

Thanks to @Philpax I've got a quick fix but please fix properly asap

**Comment by tanema** [comment]
@GhostApps That is as is originally designed. That will not change unless _no_iter_next is set. However if you use the PaginatedIterator then it will be page-restricted and will not automatically fetch the next page

**Comment by tanema** [comment]
As I am pretty new to python, I just touched up the work done by @emdemir and merged the PR without thinking through how the iteration of the collections is. What would be preferred in this situation?

I *could*
- pass no_iter_next to the collection to keep it iterating just a single page
- I could just disable the auto fetching of the next page and just have you rely on fetching the next page yourself, That would simplify the code and the interface
- I could switch how this all works, the collection is only for one page and the iterator will iterate through all of the pages automatically. This might be a bit more friendly to use this way

**Comment by Philpax** [comment]
As an end-user, I'd like the option to have both: automatic pagination, and being able to paginate individually. Ideally, the former's all I would need, but we need the latter as we need to retry requests when the Shopify servers fail to respond.

So, I'd be looking for something that can offer the following:

- getting all of the resources for a page
- advancing to the next page
- retrying resource retrieval if required without advancing the page

I can do this with the current API, but it's a bit fiddly. Perhaps something like the following pseudocode (this is just a broad sketch, I'm just illustrating the flow that would work for my use case):
```python
collection = shopify.Order.find(limit=100)
while collection.has_next_page():
    for retry_count in range(0, 5):
        try:
            resources = collection.get_data()
            # do something with resources
            collection.advance_page()
            break
        except:
            # some retry logic
```
and then additional iterators can be implemented on top of this which implement iterating over pages and iterating over elements (and doing the pagination internally). It may be worth decoupling `ShopifyResource` from "visible" pagination entirely - possibly a `paginate` method that returns another class that can be used to page through?

I think the key thing here is to keep these concerns separate and handled by different iterators, so that there isn't any unexpected behaviour: you'll know exactly what you'll get depending on which iterator you use, so you won't get any surprises like `len` changing.

There's a lot of design possibilities here, but I think the most important features are consistent, non-confusing behaviour and full control of requests for when it's needed. Let me know if you need me to clarify any of this.

**Comment by UnicycleJonathan** [comment]
It's important that `no_iter_next` be the default behavior here, and only allow automatic iteration of subsequent pages if the caller has explicitly asked for that via a parameter. Otherwise, this isn't backwards compatible and will likely introduce a lot of serious bugs and runaway code for people who are upgrading.

As mentioned above, existing code that does implicit iteration via ` for order in shopify.Order.find(limit=5):` is expecting to iterate over at most 5 orders, but with the new behavior this will iterate over all orders in the entire shop.

This will likely break almost every Python client so it's important to invert the default behavior.

**Comment by tanema** [comment]
Okay, I have changed my Pr to make no_iter_next to default to True. I will release this tonight so that you can use this and it will be easier to use. I will be a breaking release in case anyone has built on top of the current behaviour
