### ISSUE TITLE
cursor-based pagination not working (header name case-sensitivity?)

### ISSUE THREAD

**Issue by dasony** [Shopify/shopify_python_api#357]
I am trying to implement the new cursor-based pagination, with ShopifyPythonAPI/6.0.1 on Python/2.7.16 and pyactiveresource 2.2.0. I am testing with the API version 2020-10.

`has_next_page()` always returns false for me even when there are more items. Looking at your source code, `PaginatedCollection`'s `__parse_pagination` method looks for `metadata['header']['Link']` yet for some reasons, all header names are in lower-cases on my environment.

```
>>> p = shopify.Product.find(limit=3)
>>> p.has_next_page()
False
>>> p.metadata['pagination']
{}
>>> p.metadata['headers']['link']
'<https://STORE.myshopify.com/admin/api/2020-01/products.json?limit=3&page_info=CURSOR>; rel="next"'
>>> p.metadata['headers']['Link']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'Link'
```

on a side note, it would be nice if we could retrieve page_info value from PaginatedCollection, so I can use it to fetch the next page. This way I don't need to keep the original page object to access the next page. I see `shopify.Product.find(page_info=CURSOR)` works, although i would feel better if it was documented. 

Thanks.

**Comment by tanema** [comment]
What version of python are you using? This is very confusing, it should not be lowercase l on link. I will see why that might be

To fetch the next page you can just call `p = shopify.Product.find(from_=page.next_page_url)` So all that you need to save, and can link in your views is the next page url and previous page url.

**Comment by tanema** [comment]
Okay I have asked our pagination team and it seems like the header is consistently returned as `Link` so something else may be going on here.

It seems like there was an issue in urllib quite a few years ago where this happened https://github.com/urllib3/urllib3/issues/236 but was supposed to be fixed around 2017

It might be behaviour to expect. so I will try to add in a check for both cases

**Comment by boxcleverliam** [comment]
I have noticed today that in roughly 1% of responses from Shopify's REST API, the HTTP header names are lowercase.
I have not seen much discussion about it, and it is not made clear in Shopify's documentation, so I want to share this info somewhere useful.
But I confirm from my observations today that we can expect both "Link" and "link", both "X-Shopify-Shop-API-Call-Limit" and "x-shopify-shop-api-call-limit".
