### ISSUE TITLE
shopify.Order.find for list of customer_ids

### ISSUE THREAD

**Issue by bockjo** [Shopify/shopify_python_api#371]
Dear team,

I would like to retrieve Order data for a list of customers. It doesn't work as indicated below:

`shopify.Order.find(limit=250,status="any",customer_id="2136264509507,2136284509567")`

Can you please assist?

**Comment by tanema** [comment]
Can you use an array?

`shopify.Order.find(limit=250,status="any",customer_id=[2136264509507,2136284509567])`

**Comment by RalphMarks** [comment]
Hi @tanema 

I was trying to create a similar request using a list of customer ids, the requests were successful until a couple of days ago, does the library still supports this kind of requests?

**Comment by Paulinakhew** [comment]
Hey @bockjo I've implemented retrieval of orders using `customer_id` in #466
