### ISSUE TITLE
400 Error while updating discount code in checkout

### ISSUE THREAD

**Issue by rutuja-zinrelo** [Shopify/shopify_python_api#397]
I am using shopify python api to update the discount code in checkout. Below are the steps - 
1. Retrieve the checkout using, 
checkout = shopify.Checkout.find('6ad53674ac258e67cac363921af7d6c2')
2. update the discount code,
checkout.discount_code = 'CADAD12'
3. Save the checkout, 
checkout.save()

I get the following error while saving the checkout,

Response(code=400, body="{"errors":{"credit_card":"must be a hash"}}")

Please help with this issue. 

Also, please let me know if there is any other way to apply the discount code to the checkout using shopify_python_api

**Comment by mllemango** [comment]
Hi @rutuja-zinrelo, are you still running into this problem? While I'm looking into it, would you mind providing the version of shopify_python_api as well as the API version (2020-07, 2020-01 etc) that you're on?

**Comment by paulomarg** [comment]
Hi all, I've actually taken a look at this issue before and it seems to be originating in the API itself. I've reported it to the appropriate team, and they are investigating it further.

Apologies for not updating this before, I'll keep you posted on any new developments.

**Comment by Trimakas** [comment]
Hi was this ever solved? I'm getting the exact same error.. Even when just updating a note as a test.

**Comment by gplhegde** [comment]
Getting the same error. Is this issue solved yet?
