### ISSUE TITLE
The library is not thread-safe

### ISSUE THREAD

**Issue by dylanahsmith** [Shopify/shopify_python_api#4]
ActiveResource doesn't seem to be suitable for multi-threaded applications because state is stored on the class that multiple threads may want to modify and use at the same time.

Perhaps this could be solved by storing the connection in a thread-local variable.  In this way, a new connection could lazily be created for each thread when the ShopifyResource.connection property is accessed, and no locking would be needed in order to concurrently make requests from different threads.

**Comment by dave4jr** [comment]
Hey @dylanahsmith Was just curious if you ever had success implementing this and if so, why did you guys decide to not move forward with integrating this commit? I'm working on something similar and was just curious what your thoughts are on this. Thanks!

**Comment by dylanahsmith** [comment]
> Was just curious if you ever had success implementing this

See the commit that closed this issue (https://github.com/Shopify/shopify_python_api/commit/c3a344f12828d545d3a1dcaba217d4443a286e95)

> if so, why did you guys decide to not move forward with integrating this commit?

I'm confused, the issue was closed by integrating that commit.  The code on master is pretty similar, although has since been updated to support python 3.

**Comment by dave4jr** [comment]
Yeah I saw that you committed it to a feature branch, but I wasn't sure if you guys actually merged it into a release. Sorry that was my fault for not looking close enough.
