### ISSUE TITLE
No Payout option in this python api?

### ISSUE THREAD

**Issue by Stefan2142** [Shopify/shopify_python_api#401]
I was looking through the source code and couldnt find - how to find all payouts for a specific date? [This](https://shopify.dev/docs/admin-api/rest/reference/shopify_payments/payout?api[version]=2020-07) endpoint.

**Comment by tanema** [comment]
I don't believe it is implemented, but it is pretty trivial to implement it yourself

```python
from shopify import ShopifyResource


class Payout(ShopifyResource):
    pass
```

**Comment by Stefan2142** [comment]
Sorry, not that good with Python still :)

**Comment by Alchez** [comment]
Adding a code example here based on @tanema's suggestion, just in case someone stumbles onto this:

```python
from shopify import ShopifyResource


class Payout(ShopifyResource):
    _prefix_source = "/shopify_payments/"

Payouts.find()  # retrieve all payouts
Payouts.find(id)  # retrieve a particular payout by ID
```
