### ISSUE TITLE
shopify.ApplicationCharge.create:  expected string or bytes-like object

### ISSUE THREAD

**Issue by Marijus** [Shopify/shopify_python_api#402]
I'm trying to create charge:

```
application_charge = shopify.ApplicationCharge.create(
        {
            'name': 'My public app',
            'price': 123,
            'test': True,
            'return_url': 'https://domain.com/approve'
        }
    )


```

and I get this error:

`TypeError: expected string or bytes-like object`

Any ideas how to fix this?

**Comment by andyw8** [comment]
Hi @Marijus
  
Could you please share a full stack trace, and also which version of Python you're using.

**Comment by Marijus** [comment]
Hey @andyw8 ,

`Python 3.8.3 (default, Jul  8 2020, 14:27:39) `


```
Traceback (most recent call last):
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/marijus/workspace/pod/users/views.py", line 204, in select_plan_selected
    application_charge = shopify.RecurringApplicationCharge.create(attributes={'name': 'ENTREPRENEUR', 'price': 9.99, 'return_url': 'https://myapp.com', 'trial_days': 30})
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/pyactiveresource/activeresource.py", line 449, in create
    resource = cls(attributes)
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/shopify/base.py", line 180, in __init__
    prefix_options, attributes = self.__class__._split_options(attributes)
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/pyactiveresource/activeresource.py", line 467, in _split_options
    if key in cls._prefix_parameters():
  File "/Users/marijus/workspace/virtualenvs/pod/lib/python3.8/site-packages/pyactiveresource/activeresource.py", line 735, in _prefix_parameters
    for match in template.pattern.finditer(path):
TypeError: expected string or bytes-like object

```

**Comment by andyw8** [comment]
@Marijus Could you try pass the price as a string, i.e. `"9.99"` rather than `9.99`?

**Comment by Marijus** [comment]
@andyw8 I've tried it, that does not help. I've tried json.dumps(charge_attributes) and passing a string to it but then it gives you an error that it expects a dictionary (object does not have .items() method)

**Comment by andyw8** [comment]
@mariaacle Ok, could you show what your code is doing with the `application_charge` (around line 204 in your `views.py`).

**Comment by Marijus** [comment]
@andyw8 it's very simple:

```
@login_required
def select_plan_selected(request, plan_name):
    charge_data = {
        "test": "true",
        "name": "Basic",
        "price": "15.0",
        "return_url": "http://127.0.0.1:8000",
    }
    application_charge = shopify.RecurringApplicationCharge.create(attributes=charge_data)

    return render(request, "select_plan.html")
```

**Comment by JBKahn** [comment]
I know python but not this library. Hmmm. What URL are you using?

Looking at the code: https://github.com/Shopify/pyactiveresource/blob/master/pyactiveresource/activeresource.py#L735
It seems unlikely to be commenting on the parameters you're passing into the function.

**Comment by smubbs** [comment]
I've had a similar problem as above for a few days. 

My solution was a simple as having to re-initialise the Shopify Session prior to creating the RecurringApplicationCharge.

**Comment by Marijus** [comment]
@smubbs 

That solved my issue. Thank you!

**Comment by smubbs** [comment]
It would be really nice if the error was more meaningful for this. It would save a lot of confusion.

**Comment by cderinbogaz** [comment]
Agree with @smubbs. I also had the same problem and it took hours to find this. Googling error itself doesn't help much as well.

**Comment by andyw8** [comment]
Re-opening as we are still seeking a better solution for this.

**Comment by cderinbogaz** [comment]
@andyw8 Thanks for re-opening. I also have the same problem with ApplicationCharge.find command. Haven't found an open issue about this one. Shall I create a new one?

**Comment by andyw8** [comment]
@cderinbogaz It maybe be the same underlying problem, but feel free to create a separate issue for that.
