### ISSUE TITLE
How about change site when doing find?

### ISSUE THREAD

**Issue by jiamo** [Shopify/shopify_python_api#405]
In readme for private App there is :

    shopify.ShopifyResource.set_site(shop_url)

This seem set `ShopifyResource` globally.  How about concurrent change the site and at the same time another thread is doing  a long job

    shopify.Product.find()

Or change an another word.  For private App. How can we find two private App in one process with two thread?

**Comment by tanema** [comment]
ShopifyResource uses threadlocal variable. It should work perfectly fine in multiple threads. 

As for your question about private app, I am not sure what you would be using 2 different private apps for other than trying to get around our throttling mechanisms. If you are using them for a legitimate reason,  I would still say finish your task with one and then move onto the next.
