### ISSUE TITLE
when concurrently find product one by one will cause api limit

### ISSUE THREAD

**Issue by jiamo** [Shopify/shopify_python_api#406]
Is there some possible way like this:

     shopify.Product.find(id=[1, 2, 3])

This will merge my request into small one

**Comment by tanema** [comment]
No there is no current way to query products by ids like that from this library or even from the REST API. If you want something like that, you might be better off constructing a graphql query for something like that. Something like this:

```graphql
{
  product(id: "") {
    handle
  }
  product(id: "") {
    handle
  }
  product(id: "") {
    handle
  }
}
```
