### ISSUE TITLE
Gift Card Search fails

### ISSUE THREAD

**Issue by ChaseGuru** [Shopify/shopify_python_api#411]
Code:
```
giftCards = shopify.GiftCard.search(disabled_at=None)
```

Throws:
```
kcbd_api_1         | Traceback (most recent call last):
kcbd_api_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
kcbd_api_1         |     response = get_response(request)
kcbd_api_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
kcbd_api_1         |     response = self.process_exception_by_middleware(e, request)
kcbd_api_1         |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
kcbd_api_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
kcbd_api_1         |   File "/opt/kulcbd/api/shopify_app/views.py", line 18, in giftCard
kcbd_api_1         |     giftCards = shopify.GiftCard.search(disabled_at=None)
kcbd_api_1         |   File "/usr/local/lib/python3.8/site-packages/shopify/resources/gift_card.py", line 24, in search
kcbd_api_1         |     return cls._build_list(cls.get("search", **kwargs))
kcbd_api_1         | AttributeError: type object 'GiftCard' has no attribute '_build_list
```

Simple fix - MR incoming

**Comment by andyw8** [comment]
Hi @chasacha, which version of the library were you using here?

**Comment by andyw8** [comment]
And also which version of pyactiveresource ?

**Comment by andyw8** [comment]
(It seems this is due to #29 pyactiveresource so would impact v2.2.0 or later)

**Comment by ChaseGuru** [comment]
@andyw8 This issue effected me using "==8.0.2".

I lost my link to the diff in pyactiveresource, but as far as I can tell you don't cap the version of activeresource your library uses, so it may use the latest.  I also saw that you're using _build_collection in two other places, so I'm guessing this has been a bug for as long as those two places were changed but wasn't noticed.  This was the only spot using the now non-existant function `_build_list`

**Comment by ChaseGuru** [comment]
I haven't tested yet tbh - I'm working on that now.

**Comment by ChaseGuru** [comment]
Okay, my change officially fixed me getting a error about calling that function.  It's now complaining about my shop URL

**Comment by ChaseGuru** [comment]
Interestingly, now I get this:
```
Not Found: https://kulcbd-test.myshopify.com/admin/api/2020-07/gift_cards/search.json?query=disabled_at%3Anull
```

Which is strange because the URL works in my bruiser, although I can't get it to query where disabled is empty/null. (it always returns nothing if I do null or anything similar)

**Comment by ChaseGuru** [comment]
Okay, that issue is due to my test store probably.  It looks like it's now working correctly - so my merge request should be good

**Comment by mkevinosullivan** [comment]
👋  I'm going to close this issue as _v8.0.3_ has been released with your fix included.

Thank you very much for the contribution!  It's very much appreciated.
