### ISSUE TITLE
Will the Python API support the new session token authentication?

### ISSUE THREAD

**Issue by sillycube** [Shopify/shopify_python_api#415]
Since [the new auth](https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens) has been released in July, is it going to be supported in this API? 

From the doc, I can activate a session like this:
```
session = shopify.Session(shopname, API_version, access_token)
shopify.ShopifyResource.activate_session(session)
```

where the access token is given via OAuth.

Now how can I do this under JWT Auth? I only have these variables decoded from JWT token: 'iss','dest','aud','sub','exp','nbf','iat','jti','sid'

**Comment by paulomarg** [comment]
Hi @sillycube! At this time we don't have plans for including JWT support to this library, but we may look into ways of making this easier in the future.

To support JWT authentication, you will need to handle the token yourself. The tutorial has a lot of great information on how to authenticate your app and make requests, and the payload fields you mentioned contain all the information you'll need to make authenticated requests to the Admin API.

**Comment by ascheucher** [comment]
Python API really doesn't get the attention it deserves. Way behind the ecosystem... :/

**Comment by paulomarg** [comment]
I'm closing this issue as it won't lead to any changes in the code for now, but I've shared the feedback internally. We're keeping it under consideration in our future plans.

Thank you for raising this!

**Comment by davidmontgom** [comment]
Shopify I have to say your dev team is a total wreck
