### ISSUE TITLE
How to set default address

### ISSUE THREAD

**Issue by leocxy** [Shopify/shopify_python_api#417]
# Issue summary

Hi, I tried to set an address as default address. But I can't find any docs about that action. 

`
address_id = '123123'
address = shopify.Address.find(address_id)
print(address.default)
address.default = True
address.save()
`

## Actual behavior

Here is the exception

`Response(code=406, body="b''", headers={'Date': 'Mon, 28 Sep 2020 20:43:06 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Set-Cookie': '__cfduid=da4958ae7130047788d355069273e316f1601325786; expires=Wed, 28-Oct-20 20:43:06 GMT; path=/; domain=.myshopify.com; HttpOnly; SameSite=Lax', 'X-Sorting-Hat-PodId': '47', 'X-Sorting-Hat-ShopId': '29826056240', 'Referrer-Policy': 'origin-when-cross-origin', 'X-Frame-Options': 'DENY', 'X-ShopId': '29826056240', 'X-ShardId': '47', 'X-Stats-UserId': '', 'X-Stats-ApiClientId': '4219035', 'X-Stats-ApiPermissionId': '210404048944', 'HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT': '1/80', 'X-Shopify-Shop-Api-Call-Limit': '1/80', 'X-Shopify-API-Version': '2020-07', 'Strict-Transport-Security': 'max-age=7889238', 'X-Request-Id': 'be5dd16d-f851-496a-b72f-23ee523ebbd6', 'X-Shopify-Stage': 'production', 'Content-Security-Policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.us.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=error_404&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Ferrors&source%5Bsection%5D=admin_api&source%5Buuid%5D=be5dd16d-f851-496a-b72f-23ee523ebbd6", 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block; report=/xss-report?source%5Baction%5D=error_404&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Ferrors&source%5Bsection%5D=admin_api&source%5Buuid%5D=be5dd16d-f851-496a-b72f-23ee523ebbd6', 'X-Dc': 'gcp-us-central1,gcp-us-central1', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '05780d7c870000eea2090e9200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5da04b740fa7eea2-AKL', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'}, msg="Not Acceptable")
`

### Version

Python 3.8.5
ShopifyAPI==8.0.2
OS: MacOS

**Comment by paulomarg** [comment]
Since the library doesn't support nested saves, this ends up calling `/addresses/<id>.json`, when we would want it to PUT to `/customers/<customer_id>/addresses/<id>/default.json`, [as per the API reference](https://shopify.dev/docs/admin-api/rest/reference/customers/customer-address#default-2020-07).

To work around this, you'll need to manually trigger the PUT request. One way to do that is to call:
```python
shopify.Customer.put("%s/addresses/%s/default" % (customer_id, address_id))
```
Hope this helps!

**Comment by leocxy** [comment]
> Since the library doesn't support nested saves, this ends up calling `/addresses/<id>.json`, when we would want it to PUT to `/customers/<customer_id>/addresses/<id>/default.json`, [as per the API reference](https://shopify.dev/docs/admin-api/rest/reference/customers/customer-address#default-2020-07).
> 
> To work around this, you'll need to manually trigger the PUT request. One way to do that is to call:
> 
> ```python
> shopify.Customer.put("%s/addresses/%s/default" % (customer_id, address_id))
> ```
> 
> Hope this helps!

Well, Thank you very much. Your solution much more easy 

my solution was...

```python
url = '{}/customers/{}/addresses/{}/default.json'.format(
    self.api.ShopifyResource.get_site(),
    customer.id,
    address_id,
)
requests.put(url, headers=self.api.ShopifyResource.get_headers())
```
