### ISSUE TITLE
When finding discount codes and order in shopify it sometimes gives an error -  [API] Invalid API key or access token (unrecognized login or wrong password)

### ISSUE THREAD

**Issue by rutuja-zinrelo** [Shopify/shopify_python_api#419]
I am using shopify python api to find the order details and the discount code details. 

shopify_python_api - 7.0.2
shopify API version 2020-01. 

When I make these two calls,
shopify.DiscountCode.find(coupon_id, price_rule_id)
shopify.Order.find(order_id, fields='discount_codes, email')

they fail sometimes with an error code 401 - [API] Invalid API key or access token (unrecognized login or wrong password)

Need help with this.

**Comment by jahazieldom** [comment]
I am having the same problem with Orders.find only with the id argument, so far this day there are more than 100 events
