### ISSUE TITLE
FulfillmentOrders

### ISSUE THREAD

**Issue by jitendra12693** [Shopify/shopify_python_api#420]
# Issue summary

**shopify.FulfillmentOrders.find(fulfillment_order_id, order_id=OrderId)**  I am not able to get result for this method
When calling this method,  I am getting this issue
**Not Found: https://demo.myshopify.com/admin/api/2020-10/orders/2791579517090/fulfillment_orders/2557369221282.json**
## Expected behavior

This should return specific fulfillment order
**https://demo.myshopify.com/admin/api/2020-10/fulfillment_orders/2557369221282.json**

## Actual behavior

It's not returning fulfillment records

- `shopify_python_api` version:
- `pyactiveresource` version:
- Shopify API version used (e.g. `'2020-10'`):

**Comment by andyw8** [comment]
Hi @jitendra12693 

It looks like you may have a typo in the API version, `2020-0` rather than `2020-10`?

**Comment by jitendra12693** [comment]
Hi andyw8,

Not typed URL statically. Its generation after calling this function **shopify.FulfillmentOrders.find(fulfillment_order_id, order_id=OrderId)** from shopify python library.
