### ISSUE TITLE
shopify.Collect.find_first is giving ResourceNotFound. How can I handle this exception?

### ISSUE THREAD

**Issue by sillycube** [Shopify/shopify_python_api#425]
# Issue summary

Write a short description of the issue here ↓

I tried to copy the find_first function in Custom Collection,

```
class CustomCollection(ShopifyResource, mixins.Metafields, mixins.Events):
    def remove_product(self, product):
        collect = shopify.Collect.find_first(collection_id=self.id, product_id=product.id)
        if collect:
            collect.destroy()
```

However, it was giving me ResourceNotFound. If it's going to raise ResourceNotFound, collect will not equal to None

## Expected behavior

find_first will return None and return the value to collect

## Steps to reproduce the problem

1. just run the line `collect = shopify.Collect.find_first(collection_id=123, product_id=456)` in your app after the session is authenticated

## Specifications

- `shopify_python_api` version: 8.0.4
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`): 2020-07

**Comment by paulomarg** [comment]
Thank you for the detailed report. The idea behind throwing an error instead of returning `None` here is that it allows for your app to handle all 404 errors in a more uniform way.

Is there any particular reason you feel that using a try-except block to set `collect` to `None` isn't an acceptable solution if you want to work around the error?

**Comment by sillycube** [comment]
I don't know what is put in the try except. For a django model object, I can use 

```
try: 
        ....
except MyModel.DoesNotExist:
```
For ResourceNotFound, I don't know what exception to substitute DoesNotExist. There are too few sample codes. I can only find that ResourceNotFound is a class defined by pyActiveResource

**Comment by paulomarg** [comment]
As you mentioned, this exception comes from pyactiveresource. You could catch it with something like this:

```python
import pyactiveresource
    try:
        shopify.Collect.find_first(collection_id=123, product_id=456)
    except pyactiveresource.connection.ResourceNotFound as err:
        # Handle your error here
    except Exception as err:
        # Hint: err.__class__ is pyactiveresource.connection.ResourceNotFound in this case
```

As I mentioned before, this isn't necessarily the nicest way of dealing with such an error. You may want to consider handling all exceptions in a central place in your application and detect this exception there so if you get this message from a different view, you'll be able to show the same error page.

**Comment by sillycube** [comment]
Thanks, I will try it soon.
