### ISSUE TITLE
Cannot create variant to a product

### ISSUE THREAD

**Issue by sillycube** [Shopify/shopify_python_api#427]
# Issue summary

Write a short description of the issue here ↓
I try to create a variant and add to a product but it doesn't work. 

    productID = 97596047376
    product = shopify.Product.find(productID)
    print(f'editing product title = {product.title}')

    v = shopify.Variant()
    v.title = 'test_variant_by_byob'

    print(f'no of varaints 1 = {len(product.variants)}')
    product.add_variant(v)
    print(f'variant id = {v.id}')
    print(f'no of varaints 2 = {len(product.variants)}')

## Expected behavior

The new variant should be created on the admin panel. But nothing is changed now

What do you think should happen?

No idea. I tried to copy code from [test cases](https://github.com/Shopify/shopify_python_api/blob/ce1e2e67ee55fde98902c7441f42fa835859568f/test/product_test.py) and [Shopify Python API Cheatsheet](https://github.com/troyshu/shopify-python-api-cheatsheet)

## Actual behavior

What actually happens?

The no of variant doesn't change at all. But there is no error message. My output:

    editing product title = Coco
    no of varaints 1 = 6
    variant id = None
    no of varaints 2 = 6

## Steps to reproduce the problem

Just create a simple view function and paste the code after authentication. 

## Specifications

- `shopify_python_api` version: 8.0.4
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`): 2020-07
- python: 3.8

**Comment by mllemango** [comment]
Hi @sillycube! I'm able to reproduce this error on my end. A few thoughts:
1. Could you try adding options to your test variant? It looks like your product has pre-existing variants, so the new variant you are creating should reflect the same number of options as others. e.g.
```
 v.title = 'test_variant_by_byob'
 v.option1 = 'test option 1'
 v.option2 = 'test option 2'
```

2. it also looks like `product` doesn't update when you add a new variant, could you replace your last line with 
```
print(f'no of varaints 2 = {len(shopify.Product.find(productID).variants)}')
```
to force `product` to refresh?

**Comment by sillycube** [comment]
Yes, I find out the product has pre-existing options which make it not able to create a new variant. 

Also, I try to find the variant:
```
variant = shopify.Variant.find(id=659906035728, product_id = 97595228176)
print(f"len = {len(variant)}, type = {type(variant)}")
```
The output:
len = 1, type = <class 'shopify.collection.PaginatedCollection'>

I try to find variant with id only 
`variant = shopify.Variant.find(id=659906035728)`

The output:
len = 50, type = <class 'shopify.collection.PaginatedCollection'>

So the variant ids may be duplicated across different products? If I need to get the unique variant, I must input both the product id and variant id?

This part is misleading since I assume `shopify.[object].find` only gives me a single object

**Comment by mllemango** [comment]
Hey @sillycube, sorry about the late response! The reason you're getting output "len = 50" is because there is a slight syntax error in your code. 
You should be using `shopify.Variant.find(659906035728)` instead of `shopify.Variant.find(id=659906035728)`

Are you still having trouble updating variants otherwise?

**Comment by sillycube** [comment]
Yes, I try to update variant title with Shopify console. But it can't save:
>>> v = shopify.Variant.find(32920357830746)
>>> v.title 
'Bundle26_2020-11-11T04:12-05:00_659908853776,1,659905314832,1,659906592784,1'
>>> v.title = '123'
>>> v.title
'123'
>>> v.save()
True
>>> v.title
'Bundle26_2020-11-11T04:12-05:00_659908853776,1,659905314832,1,659906592784,1'

**Comment by mllemango** [comment]
Hey @sillycube, you have again come across some unique behaviour of our api.
Variant Title is a concatenation of the variant options, thus if you want to change the title, you have to change the option! You can see [here](https://shopify.dev/docs/admin-api/rest/reference/products/product-variant#update-2020-10) that the documentation mentions updating the "title" of a variant, but the body of the request is actually an option.
Thanks for bringing this up, the documentation will be updated so the use of `title` is clarified.
