### ISSUE TITLE
updating variant price has no effect and does not throw an error

### ISSUE THREAD

**Issue by samLozier** [Shopify/shopify_python_api#433]
# Issue summary
Trying to change the price of an existing variant does not seem to have any effect and is possibly failing silently

## Expected behavior
Upon saving I'd expect the price to change. I've allowed for some lag, around 20 minutes, and have still not observed a change. 

## Actual behavior
Saving appears to succeed, or at least does not throw an error however no changes are made to the price. This is true when checked immediately in the code block or minutes later manually through the web UI

## Steps to reproduce the problem
```
for r in records[:1]:
    with shopify.Session.temp(r['session_id'].site, '2020-07', r['session_id'].token):
        if shopify.Variant.exists(r['variant_id']):
            v = shopify.Variant.find(r['variant_id'])
            if v.price != r['LS PRICE']:
                print(v.id, v.price,) #print existing price and ID
                v.price = r['LS PRICE']  #update to new price, in this case 699.99
                print(v.price)
                v.save()
                #did it change?
                new = shopify.Variant.find(r['variant_id'])
                print(new.id, new.price)
```

```
#output
36271051571361 850.00
699.99
36271051571361 850.00
```

## Specifications

- `shopify_python_api` version: 8.0.2
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`):2020-07

**Comment by samLozier** [comment]
I believe I've figured out why the update wasn't working and a temporary work around. Starting with api version 2020-04 (2020-01 works) shopify stopped allowing the compare-at-price to be set to 0 via the api, though strangely you can still set it to 0 in the UI. From 2020-04 forward they will only take a value greater than the price or Null. This apparently causes an issue when you fetch a variant that currently has a compare-at-price of 0 via the API and then try modify that variant and save it with this package. 

I was able to get around this limitation by changing the API version to 2020-01, but it fails if I change the API string to 2020-04.

**Comment by paulomarg** [comment]
Thanks for the detailed report @samLozier, we'll look into it and see how to solve this issue!

**Comment by samLozier** [comment]
I did some more digging into this and since the source of the issue seems to be Shopify itself, IMO it would be helpful if this package could one or more of the following to help manage problem: 

- Raise some sort of future warning about setting compare-at < price regardless of API version 
- Fail loudly when a Put operation fails and return the error message to the user/stdout
- Override the API version to 2020-01 in instances where this would matter. 
- In instances where only the price is to be modified, remove the "compare-at-price" attribute from the variant object prior to saving similar to how the inventory quantity attribute is being removed on line 24 here 
https://github.com/Shopify/shopify_python_api/blob/master/shopify/resources/variant.py

This also raises an interesting issue with smart collections. I know of a number of shops that use a "compare at price is = 0" condition to generate collections of full-price products and this change from Shopify seems to remove that functionality. Here are several threads from the shopify community highlighting the same problem:
https://community.shopify.com/c/Shopify-APIs-SDKs/Compare-at-price-required-for-graphql-2020-04-Admin-api/td-p/821507
https://community.shopify.com/c/Shopify-APIs-SDKs/quot-errors-quot-quot-compare-at-price-quot-quot-Compare-at/td-p/889386
https://community.shopify.com/c/Shopify-APIs-SDKs/Create-Product-API-throw-Error-amp-quot-Compare-at-price-needs/td-p/803902
https://community.shopify.com/c/Shopify-APIs-SDKs/Unable-to-reset-compare-at-price/td-p/898733

**Comment by samLozier** [comment]
I noticed my old bug report was still open and thought I'd add some additional documentation. 

Apparently, this breaking change was reverted by Shopify and it's now possible to set prices without any validation limits again. I believe this bug report can be closed. 

https://shopify.dev/changelog/pricing-validations-removed-from-all-api-versions
