### ISSUE TITLE
Error on updating collection

### ISSUE THREAD

**Issue by blob84** [Shopify/shopify_python_api#436]
# Issue summary

Write a short description of the issue here ↓
Error when I try to update an existing collection adding a product

## Expected behavior

What do you think should happen?
Collection updated with the new product

## Actual behavior

What actually happens?
Error is given

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
AttributeError: 'PaginatedCollection' object has no attribute 'id'

## Steps to reproduce the problem

1.     collection = shopify.CustomCollection.find(title="Cat1")
1.        product = shopify.Product.find(product_id="6053216354471")
1.        col = shopify.Collect(collection_id=collection.id, product_id=product.id)

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- `shopify_python_api` version: 7.0.3
- `pyactiveresource` version:
- Shopify API version used (e.g. `'2020-07'`):

**Comment by samLozier** [comment]
are you saving the new collect that you're making, the code you've showed doesn't look like you are? 

give this a try:
```
col = shopify.Collect(collection_id=collectionid, product_id=product.id)
col.save()
```
