### ISSUE TITLE
AttributeError: partially initialized module 'shopify' has no attribute 'Session' (most likely due to a circular import)

### ISSUE THREAD

**Issue by klodoma** [Shopify/shopify_python_api#437]
# Issue summary

I am trying out this api code, but I cannot get it running. I am no python expert, but I am getting this error:

```AttributeError: partially initialized module 'shopify' has no attribute 'Session' (most likely due to a circular import)```

```
  File "C:\DevKit\Python\Python38\lib\json\decoder.py", line 3, in <module>
    import re
  File "C:\DevKit\Python\Python38\lib\re.py", line 127, in <module>
    import functools
  File "C:\DevKit\Python\Python38\lib\functools.py", line 18, in <module>
    from collections import namedtuple
  File "c:\Users\andy\OneDrive\ONLINE SHOP\code\collections.py", line 10, in <module>
    shopify.Session.setup(api_key=API_KEY, secret=API_SECRET)
AttributeError: partially initialized module 'shopify' has no attribute 'Session' (most likely due to a circular import)
```
```
import shopify

shopify.Session.setup(api_key=API_KEY, secret=API_SECRET)
session = shopify.Session(SHOP_URL, API_VERSION)
```

## Expected behavior

No error should be displayed

## Actual behavior

Error is displayed

## Specifications

- `shopify_python_api` version: 8.0.4
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`): 2020-10

**Comment by mllemango** [comment]
Hey @klodoma, I believe this error occurs when you try to import a module that has the same name as your file. Is your file called `shopify.py` as well?

**Comment by klodoma** [comment]
no, my file was called `collections.py`, I've renamed it to `foo.py` and seems to solve the issue. 

Not sure if this could be solved better, would be nice :)

**Comment by Paulinakhew** [comment]
> no, my file was called `collections.py`, I've renamed it to `foo.py` and seems to solve the issue.
> 
> Not sure if this could be solved better, would be nice :)

Hey @klodoma , the reason why `collections.py` did not work for you as a file name is because python has a module named `collections` as well. You can read up on it [from the python documentation here](https://docs.python.org/3/library/collections.html). If you had
```python3
import collections
```
in your code somewhere, python would try to import the module and the file named `collections.py`, resulting in your AttributeError.
