### ISSUE TITLE
On getting token I get error 400 bad request

### ISSUE THREAD

**Issue by blob84** [Shopify/shopify_python_api#439]
Hello, I'm getting this error on access token:

`Traceback (most recent call last):
  File "test_customapp.py", line 28, in <module>
    access_token = session.request_token(request_params) # request_token will validate hmac and timing attacks
  File "/usr/local/lib/python3.7/site-packages/shopify/session.py", line 67, in request_token
    response = urllib.request.urlopen(request)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
`
This is the code:

```
`shop_url = "https://mysite.myshopify.com"
api_version = "2020-10"
state = binascii.b2a_hex(os.urandom(15)).decode("utf-8")
redirect_uri = "http://localhost/auth/callback/"
scopes = ['read_products', 'read_orders']

API_KEY = "KEY"
API_SECRET = "SECRET"
shopify.Session.setup(api_key=API_KEY, secret=API_SECRET)

newSession = shopify.Session(shop_url, api_version)
auth_url = newSession.create_permission_url(scopes, redirect_uri, state)
# redirect to auth_url
print("auth:", auth_url)

request_params = {'code': 'code', 'timestamp': time.time()}
hmac = shopify.Session.calculate_hmac(request_params)
request_params['hmac'] = hmac
print(request_params)
session = shopify.Session(shop_url, api_version)
access_token = None
#try:
access_token = session.request_token(request_params) # request_token will validate hmac and timing attacks`
```

What is wrong and what the redirect_uri is used for?
Thanks.

**Comment by ShahrukhAhmed89** [comment]
Do you have the client id parameter as none? I am having a similar 400 issue.

**Comment by tanema** [comment]
> http://localhost/auth/callback/

This is most likely wrong, it is very unlikely that you are running your local server on port 80. The redirect URI is setup in your app configuration. There is a whitelist that you setup when you created the app, this is where your redirect urls are setup. It is a list of urls that you confirm that it is safe for shopify to redirect after authentication.

It seems like you do not entirely understand how Oauth works, I suggest you look at our example here [shopify_django_app](https://github.com/Shopify/shopify_django_app) 
 for a reference on how to implement this flow, especially here: https://github.com/Shopify/shopify_django_app/blob/master/shopify_app/views.py#L21-L31 where the oauth flow is initiated. Your code is skipping several steps by creating a session and requesting the access token directly

**Comment by blob84** [comment]
I enabled the app from the merchant store, I got the required parameters from the redirect uri and I still get bad request error!
```
 def login():
    shopify.Session.setup(api_key=API_KEY, secret=API_SECRET)
   newsession = shopify.Session(shop_url, api_version)
    auth_url = newsession.create_permission_url(scopes, redirect_uri, state)
    response = requests.get(auth_url)
    # redirect to auth_url
    print("auth:", auth_url)

 def get_token():
     request_params = {
        'shop': 'myshop.myshopify.com',
        'state': 'state',
        'code': 'code', 
        'timestamp': 1606462921, 
        'hmac': 'hmac'
    }
   
    session = shopify.Session(shop_url, api_version)
    session.setup(api_key=API_KEY, secret=API_SECRET)

    return session.request_token(request_params)
```

**Comment by blob84** [comment]
OK I got the access token.
I put the auth_url in the browser where the redirect uri was filled with the required information. Login is required from the web browser.
After that I was able to run the code to request the token succesfully.
