### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify_python_api#440]
Due to https://github.com/Shopify/pyactiveresource/issues/37, Python 3.9 is not yet supported.

**Comment by smubbs** [comment]
Suggest this issue be closed ref https://github.com/Shopify/pyactiveresource/issues/37

**Comment by paulomarg** [comment]
Thanks for raising this @smubbs - I'm closing this issue @andyw8, but please re-open it if there are any other known reasons preventing us from going up to 3.9.

**Comment by andyw8** [comment]
The README needs updated - let's remove the line "This library requires Python 3.8 or lower" ?

**Comment by andyw8** [comment]
Also, let's test against 3.9 in CI?

**Comment by paulomarg** [comment]
Great points, let's keep this issue open until we do those!
