### ISSUE TITLE
Local timezone not taken into account with Order.count date parameters

### ISSUE THREAD

**Issue by rbnali** [Shopify/shopify_python_api#444]
# Issue summary

I noticed some discrepancies in the number of returned results between Order.find and Order.count in the Python Shopify API. Local timezone is taken into account with Order.find but not with Order.count. 

* Order.count(created_at_min=my_date) will return the number of orders created after `my_date` without taking the timezone into account.
* If I take Order.find(created_at_min=my_date) and add all results from pagination, I will end up with all orders created after `my_date` with timezone taken into account.

We end up with different numbers of orders even though the parameters are exactly the same.

Reproduced with `updated_at_min` parameter as well.

## Expected behavior

Order.count should take the local timezone into account.

## Specifications

- `shopify_python_api` version:  8.1.0
- `pyactiveresource` version: 2.2.0
- Shopify API version used: 2020-10

**Comment by paulomarg** [comment]
Thank you for reporting this @rbnali, we will investigate this issue.

Just so we have an easier time reproducing the issue, what is the format of `my_date` in your example?

**Comment by rbnali** [comment]
@paulomarg I did some additional tests today:
* If `my_date` is in the string format `%Y-%m-%dT%H:%M:%S`, we observe a difference in the number of results between the two methods.
* If `my_date` is in the ISO-8601 format (`%Y-%m-%dT%H:%M:%S+hh:mm` with hh:mm designating the timezone difference),  there's no difference between `Order.find` and `Order.count`.

**Comment by paulomarg** [comment]
Thanks @rbnali, that is very helpful! It seems we're using different timezones on those requests, so it should be possible to change them to behave the same way.

That being said, I'd recommend including the timezone information in your dates when possible as that helps avoid this sort of conversion issue.
