### ISSUE TITLE
metafields are not saved

### ISSUE THREAD

**Issue by blob84** [Shopify/shopify_python_api#446]
Hello, I am trying to create metafields for variants but they are not stored in shopify products:
`                        variant.add_metafield(shopify.Metafield({
                            'key': 'mykey',
                            'namespace': 'inventory',
                            'value': 'myvalue',
                            'valuet_type': 'string'
                        }))
                        variant.save()
                        product.save()
` 
When I access them, they are empty.

**Comment by paulomarg** [comment]
Hi @blob84, can you please confirm which version of the API you're using for that request so we can look into it?

**Comment by blob84** [comment]
version 2020-10

**Comment by mllemango** [comment]
Hey @blob84 there's a typo in `value_type`, does fixing that help?

**Comment by blob84** [comment]
the problem is not fixed, can you check?
Thanks.

**Comment by Paulinakhew** [comment]
Hi @blob84 have you tried
```
variant.destroy()
```
?

**Comment by blob84** [comment]
Hi Paulinakhew, thanks.
