### ISSUE TITLE
When is it going to support 2021-01 API version?

### ISSUE THREAD

**Issue by sillycube** [Shopify/shopify_python_api#447]
Since there is a breaking change for recurring application charge, I would like to know when is it going to support the latest API version. 

I believe that these 2 lines will be changed / removed:
```
charge = shopify.ApplicationCharge.find(charge_id)
shopify.ApplicationCharge.activate(charge)
```

Please also update the official doc.

**Comment by cderinbogaz** [comment]
When using the latest api version 2021-01, library gives an error saying that it is not supported:

`/venv/lib/python3.8/site-packages/shopify/api_version.py", line 18, in coerce_to_version
    raise VersionNotFoundError
shopify.api_version.VersionNotFoundError`
