### ISSUE TITLE
Version Not Found Error When Using API 2021-01

### ISSUE THREAD

**Issue by cderinbogaz** [Shopify/shopify_python_api#450]
# Issue summary

Write a short description of the issue here ↓
When using shopify API version 2021-01 library gives an error.

## Expected behavior

Works

## Actual behavior

`
/venv/lib/python3.8/site-packages/shopify/api_version.py", line 18, in coerce_to_version
    raise VersionNotFoundError
shopify.api_version.VersionNotFoundError
`

## Steps to reproduce the problem

1. Change the API version from shopify partner panel
2. Change the API version in latest libarary
3. Setup a session.

## Specifications

- `shopify_python_api` version: 8.1.0
- `pyactiveresource` version: 2.2.1
- Shopify API version used (e.g. `'2020-07'`): 2021-01

**Comment by mllemango** [comment]
Version 8.2.0 should fix this problem!

**Comment by cderinbogaz** [comment]
@mllemango Thanks for the answer. Shall I close the request or is it better to keep it open for planning purposes of the library? Cheers

**Comment by mllemango** [comment]
@cderinbogaz v8.2.0 was just rolled out, so let's close this issue. Re-open if this problem is still persisting though!
