### ISSUE TITLE
Cannot set price of product without variants

### ISSUE THREAD

**Issue by jordanmaurice** [Shopify/shopify_python_api#468]
# Issue summary

Creating a new product and trying to set the product price does not add the price to the product in Shopify.

```
product = shopify.Product()
product.title = "Shopify Logo T-Shirt"
product.save()                      # => True
shopify.Product.exists(product.id)  # => True
product = shopify.Product.find(product.id)
product.price = 19.99
product.save()
```

## Expected behavior

If you use the same code as the tutorial, you would expect the product to have a price of 19.99

## Actual behavior

The product has no price set.

## Steps to reproduce the problem

1. Copy code from the "Advanced Usage" section of the read me
2. Insert anywhere in your python project and run the code
3. Observe the product is created in Shopify, but has no price value set. 

## Specifications

- `shopify_python_api` version: Latest
- `pyactiveresource` version: Latest
- Shopify API version used (e.g. `'2020-07'`): Latest

**Comment by paulomarg** [comment]
Hi @jordanmaurice, thank you for reporting this. You're right, and the README shouldn't be suggesting that any more.

As per the [REST Product documentation](https://shopify.dev/docs/admin-api/rest/reference/products/product), you can only set the price for a variant, not for the product itself. We'll update the README accordingly.

**Comment by jordanmaurice** [comment]
Thanks. Can you please update it to show how to add a price to the default variant that is created with a new product? I'm struggling to get that working.

**Comment by blob84** [comment]
You can set the price to the default variant,
very shopify product has at least one default variant.
`variant = shopify.Variant()
variant.price=N
product = shopify.Product()
product.variants = [variant]
product.save()
`
