### ISSUE TITLE
Redirection 302 for PUT request via Shopify API

### ISSUE THREAD

**Issue by LucSpan** [Shopify/shopify_python_api#469]
# Issue summary

When I try to update a product, I get a `Redirection: Response(code=302,...)` error. GET requests work fine. 

Write a short description of the issue here ↓

GET requests work fine, i.e. `product = shopify.Product.find(6514193137813)` retrieves the product data.

However, if I want to update an existing product; i.e. PUT requests don't work. That is,

`product.title = 'test123'`
`product.save()`
returns a `Redirection: Response(code=302,...)`.

## Expected behavior

What do you think should happen?

The product title should've changed to `test123`. 

## Actual behavior

What actually happens?

a `Redirection: Response(code=302,...)` is returned.

`Redirection: Response(code=302, body="b'<html><body>You are being <a href="https://kosmetikliegeshopde.myshopify.com/admin/api/2020-04/products/6514193137813.json">redirected</a>.</body></html>'", headers={'Date': 'Fri, 26 Feb 2021 13:36:42 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'X-Sorting-Hat-PodId': '148', 'X-Sorting-Hat-ShopId': '40714240149', 'Referrer-Policy': 'origin-when-cross-origin', 'X-Frame-Options': 'DENY', 'X-ShopId': '40714240149', 'X-ShardId': '148', 'Status': '301 Moved Permanently', 'Location': 'https://kosmetikliegeshopde.myshopify.com/admin/api/2020-04/products/6514193137813.json', 'Strict-Transport-Security': 'max-age=7889238', 'Set-Cookie': 'request_method=PUT; path=/', 'X-Shopify-Stage': 'production', 'Content-Security-Policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=update&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=580cbfec-e653-4596-8ca1-2e83e116d9ff", 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block; report=/xss-report?source%5Baction%5D=update&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=580cbfec-e653-4596-8ca1-2e83e116d9ff', 'X-Dc': 'gcp-us-central1,gcp-us-east1,gcp-us-east1', 'NEL': '{"report_to":"network-errors","max_age":2592000,"success_fraction":0.0001}', 'Report-To': '{"group":"network-errors","max_age":2592000,"endpoints":[{"url":"https://monorail-edge.shopifycloud.com/v1/reports/nel/20190325/shopify"}]}', 'X-Request-ID': '580cbfec-e653-4596-8ca1-2e83e116d9ff', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '0880275c5800004c5c0b9ec000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '627a0e73c8454c5c-AMS', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'}, msg="Found")`

## Steps to reproduce the problem

1. connect to shop:
`API_VERSION = '2020-04'`
`shop_url = "https://%s:%s@%s/admin/api/%s" % (keys['API_KEY'][0], keys['PASSWORD'][0],keys['url'][0].split('/')[-1], API_VERSION)`
`shopify.ShopifyResource.set_site(shop_url)`    
2. find product
`product = shopify.Product.find("6514193137813")`
3. update product
`product.title = 'test23'`
`product.save()`

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- `shopify_python_api` version: 8.2.0
- `pyactiveresource` version: 2.2.2
- Shopify API version used (e.g. `'2020-07'`): 2020-04

**Comment by mllemango** [comment]
Hey @LucSpan, I tried reproducing your issue but I'm not seeing an error on my end. Might be an authentication problem if your GET request works but PUT doesn't. Can you reproduce this using postman, with the following url and body?
`https://kosmetikliegeshopde.myshopify.com/admin/api/2020-04/products/6514193137813.json`
```
{
    "product": {
        "title": "test123"
    }
}
```

**Comment by LucSpan** [comment]
I've succesfully placed a PUT request using the requests library,

import requests
    
    payload = {
               "product":{
                          "title":"My new title"
                          }
               }
    
    api_key = "xxxxx"
    password="xxxxxx"
    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    
    #send email to customer through events endpoint
    r = requests.put("https://"+api_key+":"+password+"@MYSTORE.myshopify.com//admin/api/2021-01/products/{PRODUCT_ID}.json", json=payload,  headers=headers)
    print(r)

**Comment by mllemango** [comment]
Cool! Can you confirm that you still get a 302 error with `product.save()`?

**Comment by pointpaul** [comment]
bump, same issue here. Any input ?

**Comment by Leezj9671** [comment]
Same issue now.
