### ISSUE TITLE
TypeError: _element_path() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by jordanmaurice** [Shopify/shopify_python_api#474]
# Issue summary

Unable to access InventoryLevel resource using InventoryItem ID

inventoryLevel = shopify.InventoryLevel.find(inventoryItem.id)

## Expected behavior

When given an inventoryItem.id 

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- `shopify_python_api` version:
- `pyactiveresource` version:
- Shopify API version used (e.g. `'2020-07'`):

**Comment by jordanmaurice** [comment]
Accidentally opened!

**Comment by johndowling20** [comment]
Why was this closed? Was it resolved? If so, what api version was the resolution released in?
