### ISSUE TITLE
Unable to set inventory level when creating new product/variant

### ISSUE THREAD

**Issue by jordanmaurice** [Shopify/shopify_python_api#476]
# Issue summary

I'm not sure if this is an issue with how the API works, or my code, documentation is very poor.  

Our client has an existing database of their inventory, we are using the Python Shopify API to create inventory items based on existing database values. 

Here is my code to create a new product:
```
# Start by initalizing a new product
product = shopify.Product()

# If the retail sales price is set for the item, add price variant
if (self.spr != 0):
    variant = shopify.Variant()
    variant.price = str(self.spr)

    # Add the variant to the new product
    product.variants = [variant]

    # Get the inventory item of the variant
    inventoryItem = shopify.InventoryItem.find(variant.inventory_item_id)

    # Set it to require shipping, and tracked inventory
    inventoryItem.tracked = True
    inventoryItem.requires_shipping = True

    # Save changes to the inventory item
    inventoryItem.save()

    # Update the quantity of the item 
    set_quantity = shopify.InventoryLevel.set(location_id=59545354389, inventory_item_id=inventoryItem.id, available=self.quantity)
               
# Set the rest of the attributes
product.title = str(self)
product.product_type = self.text_category
product.body_html = self.description
product.vendor = self.manufacturer
product.handle = slugify(str(self))

# This retrieves a list of image URLs
image_list = self.get_related_images_list()

product_images = []

for image_url in image_list: 
    new_image = shopify.Image()
    new_image.src = image_url
    product_images.append(new_image)

product.images = product_images

product.save()
```

## Expected behavior

According to the API docs, product variants and inventory item IDs have a 1 to 1 relationship, so if a new inventory item is initialized, I would expect that I could access an inventory_item_id using variant.inventory_item_id

## Actual behavior

What actually happens?

It raises an AttributeError for inventory_item_id

## Steps to reproduce the problem

1. Create new Shopify Product
2. Create new Variant
3. Attempt to access inventory_item_id attribute of the new variant
4. Observe that an AttributeError is raised

Really wish we could get proper documentation on how to use the library, the readme has only a basic implementation with outdated code samples.  Having documentation would certainly help to use this further.

**Comment by mllemango** [comment]
Hey @jordanmaurice, is the error occurring at the line `inventoryItem = shopify.InventoryItem.find(variant.inventory_item_id)`? If so, that would be because your new variant resource isn't saved yet, so there is no `inventory_item_id` associated with it.

**Comment by mllemango** [comment]
Hey @jordanmaurice, closing this issue. Feel free to open if this is still troubling you.

**Comment by sillycube** [comment]
Hey @mllemango,

I am also having the attribute error for inventory_item_id. 

Sentry indicates that `inventory_item_id = variant.inventory_item_id` is giving the error. But I did save the variant before. The error doesn't happen frequently.

```
def update_variant_quantity(variant, quantity):
    inventory_item_id = variant.inventory_item_id
    inventory_level = shopify.InventoryLevel.find_first(inventory_item_ids=inventory_item_id)
    shopify.InventoryLevel.set(
        inventory_item_id=inventory_item_id, location_id=inventory_level.location_id, available=quantity)
```

```
if no_of_variant >= 0 and no_of_variant < MAX_NO_OF_VARIANT:
    new_variant.product_id = latest_product_id
    new_variant.save()
else:  # used up 100 variants, need to create new product
    new_product = create_new_shopify_product(bundle)
    new_variant.product_id = new_product.id
    new_variant.save()
    create_metafield(new_product, "hidden", 1, "integer", "seo")
    first_product = shopify.Product.find(bundle.shopify_ids[0])
    copy_metafield(shopify_type, first_product, new_product)
    bundle.shopify_ids.append(new_product.id)
    bundle.save()

# set new variant quantity
update_variant_quantity(new_variant, quantity)
```

**Comment by mllemango** [comment]
Hey @sillycube, this is an intermittent issue? 🤔 If there's anymore information you can provide, I'll pass it to our API team

**Comment by sillycube** [comment]
Yes, it appears occasionally. Last night, it happened again. My Django app just sent me an error notification

My app creates a new variant and updates the inventory quantity. 

It gave:
Exception Type: AttributeError at /app_proxy/create_new_variant/
Exception Value: inventory_item_id

The function I called in create_new_variant:
`update_variant_quantity(new_variant, quantity)` 

```
# update the quantity of a variant, generated from user selections
def update_variant_quantity(variant, quantity):
    inventory_item_id = variant.inventory_item_id
    inventory_level = shopify.InventoryLevel.find_first(inventory_item_ids=inventory_item_id)
    shopify.InventoryLevel.set(
        inventory_item_id=inventory_item_id, location_id=inventory_level.location_id, available=quantity)
```

There are many users calling this create_new_variant all the time. If 

Server time: Wed, 23 Jun 2021 17:16:55 +0000
Django Version: 3.2
Python Executable: /usr/local/bin/python
Python Version: 3.9.2

**Comment by Koperundevi** [comment]
Hi. This happens to us as well. Not for every produt, but only for few. In recent days, the error ocurrence is quite more than before.

**Comment by mllemango** [comment]
If I could get the "X-Request-ID" from your failing calls that would be super helpful

**Comment by sillycube** [comment]
It happened 7 hours ago. But I can't find this X-Request-ID from Sentry / Django error notification. I can find signature, timestamp, client IP, etc but your parameter is not found.

**Comment by mllemango** [comment]
does enabling logging help?

```
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger().setLevel(logging.DEBUG)
```

**Comment by sillycube** [comment]
Yes, it helps. I also can find the X-Request-ID in Sentry. 

X-Request-Id | 0094bb53-c3a0-4afe-8d75-1927aa465a05

In Sentry, I found that it gave 422:
POST https://[my-store].myshopify.com/admin/api/2021-01/products/6843532640446/variants.json [422]
{
reason: Unprocessable Entity
}

After that, it gave AttributeError: inventory_item_id

From my debug log (the code called before): 
```
new_variant.save()
print(f"existing product: new_variant id = {new_variant.id}")
```
new_variant id is showing None as well. 

The issue also happens when I try to create a new variant with a metafield:
```
new_variant = shopify.Variant({
                "option1": get_variant_option_name(bundleID),  # caution: option cannot be repeated!
                "price": f"{price:.2f}",  # round to 2 decimal place
                "inventory_policy": "continue",
                "weight": weight,
                "weight_unit": weight_unit ,
                "metafields": [{
                     "key": "selectedVariants",
                     "value": str([(dict.get('variantID'), dict.get('quantity')) for dict in variant_dicts]),
                     "value_type": "string",
                     "namespace": SHOPIFY_METAFIELD_NAMESPACE
                }]
            })
```

X-Request-Id | d7181747-b79a-4196-8ea7-f44f569bcf01

Look like the variant is not created when I call it
