### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by PeterJCLaw** [Shopify/shopify_python_api#477]
It would be great if this package published Python wheels, so that consumers didn't need to run the package's `setup.py` as part of their install process.

I think it could be as simple as adding `bdist_wheel` to the `shipit.yml` file, though you may also want to add:
```
[bdist_wheel]
universal = True
```
to your `setup.cfg`.

Not sure if I'm missing a reason that wheels wouldn't work for this project though?

**Comment by paulomarg** [comment]
Hey @PeterJCLaw, thanks for bringing this up. We'll investigate whether that works for this project!

**Comment by PeterJCLaw** [comment]
@paulomarg is there any update on this? Wheels should work for pretty much every project at this point with very little effort but improve the experience for all consumers. For pure-python projects they're usually trivial to set up.

**Comment by PeterJCLaw** [comment]
Bot: this is waiting on a response from the maintainers.

**Comment by PeterJCLaw** [comment]
Bot: this is still waiting on a response from the maintainers.
