### ISSUE TITLE
Authentication Error with OAuth example

### ISSUE THREAD

**Issue by qq1356661768** [Shopify/shopify_python_api#486]
```
shop_url = "SHOP_NAME.myshopify.com"
api_version = '2020-10'
state = binascii.b2a_hex(os.urandom(15)).decode("utf-8")
redirect_uri = "http://myapp.com/auth/shopify/callback"
scopes = ['read_products', 'read_orders']

newSession = shopify.Session(shop_url, api_version)
auth_url = newSession.create_permission_url(scopes, redirect_uri, state)
# redirect to auth_url
```

Use the above code and fill in the corresponding value, but the error is reported:
But I use the following code according to the online tutorial:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

But it doesn't work. How to solve it.

**Comment by mllemango** [comment]
Hi @qq1356661768, what is the error you're seeing? 
(I've updated your comment for formatting)

**Comment by qq1356661768** [comment]
> 嗨@ qq1356661768，您看到的错误是什么？
> （我已经更新了您对格式的评论）

![image](https://user-images.githubusercontent.com/57861916/111558403-a9b01e80-87c9-11eb-9500-358071fb6314.png)

**Comment by mllemango** [comment]
Have you tried [this](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org)?

**Comment by mllemango** [comment]
Hey @qq1356661768, please try upgrading to the latest version 8.4.0. Hope that helps!
