### ISSUE TITLE
Apps on your Shopify store require updating before April 1, 2021

### ISSUE THREAD

**Issue by brian4342** [Shopify/shopify_python_api#488]
# Issue summary

I have been using this library a lot and I am currently using version 8.2.0
I use the library to update the prices and quantities of the stock on my store however I have been getting this warning from Shopify:

## Shopify Warning

We’re sending you this email because one or more private apps installed on your Shopify store are making calls to APIs that will be removed soon and will soon be unsupported. These apps must be updated by a developer before April 1, 2021 to continue working normally.

We encourage you to forward this email to the partner or developer who maintains your apps, and have them update your apps based on the information below. If you don’t currently have a developer maintaining your apps, you can hire a Shopify expert.

What your developer needs to know

One or more of your private apps have made deprecated API calls in the last 14 days. Support for these versions will be removed on April 1, 2021. Please update the apps listed below to API version 2020-07 or later to ensure they continue to function correctly.

Store: XXX

App: XXX
Breaking changes:

The page filter has been removed from multiple endpoints. Use cursor-based pagination instead. 
The inventoryQuantity, inventoryQuantityAdjustment, restock and other fields related to legacy inventory calls have been deprecated. 
The location_id is now required when creating fulfilment and refund requests. 
The page filter has been removed from all endpoints. Use cursor-based pagination instead. 

## Question

So my question is, Do I need to make any changes to the way that I use this library or will there be an update to address the warnings that Shopify are giving

**Comment by mllemango** [comment]
Hey @brian4342 I would recommend making the appropriate changes to the way you are using the library. We support cursor-based pagination and the other 2 points should pertain to the way you are using your resources. 
We'll work on adding these warnings into the library in the meantime. Thanks!

**Comment by brian4342** [comment]
Hi @mllemango, Thanks for the reply. 

It's not often that I download all products from the store but I can look at how to update that to cursor-based. The main thing I do is update stock levels and prices. Here is a sample of the code I use:

    # Find product based on ID
    product = shopify.Product.find(PRODUCTID)
    
    # Choose variant to update
    product.variants[0].price = NEWPRICE

    # Update Shopify quantity 
    product.variants[0].inventory_quantity = int(QUANTITY)
    
    # Save changes
    product.save()

Do you now how this code^ would be amended to follow the Shopify's new guidelines?

**Comment by mllemango** [comment]
Our recommended method is to access the [InventoryLevel](https://shopify.dev/docs/admin-api/rest/reference/inventory/inventorylevel) resource, in this case it looks like `/admin/api/2021-01/inventory_levels/set.json` is what you're looking for. Since docs are minimal for this resource, I suggest looking at the tests to see how it's being used. Let me know if you have anymore questions!

**Comment by brian4342** [comment]
Hi @mllemango, 

I have been trying to work with the inventory level. Do you think you could add more to the docs as I am not quite able to get this to work.  

I am using Shopify version 8.2.0 and setting API_VERSION to '2021-04'
I am trying to use the following code to update the quantity of a product variant using the following code:

   shopify.InventoryLevel.set(VARIANT_ID, LOCATION_ID, QUANTITY)

But this is giving the following error:
    ResourceNotFound: Not Found: https://SHOPNAME.myshopify.com/admin/api/2021-04/inventory_levels/set.json

Any ideas? I'm stumped.

**Comment by mllemango** [comment]
Hey Brian, ResourceNotFound indicates that the API can't find the specific inventory level you've specified. Can you make sure you're passing in the correct values here? InventoryLevel.set is looking for these variables to be passed in: `InventoryLevel.set(location_id, inventory_item_id, available)`

**Comment by brian4342** [comment]
Hi @mllemango, I appreciate all of this help thank you. 

I am still getting the same error. 

For the inventory_item_id, I am passing the variant_id from the product whose quantity I need to adjust. Is this the correct value to use for inventory_item_id? If not can you tell me how to extract the correct ID from a product.

For the location_id I am passing the location ID that you find in the Shopify Admin portal under settings -> location. Is this also the correct value to be passing in? The store only has a single location. 

Kind Regards

**Comment by mllemango** [comment]
No problemo.
inventory_item_id is not the same as variant_id. You'll be able to grab it from the [variant](https://shopify.dev/docs/admin-api/rest/reference/products/product-variant).

The location_id should be correct, you can triple check with the [location](https://shopify.dev/docs/admin-api/rest/reference/inventory/location) end point.
