### ISSUE TITLE
Add support for store local delivery & local pickup

### ISSUE THREAD

**Issue by jaddison** [Shopify/shopify_python_api#492]
## Overview

I'm not sure if this is adding a new feature or modifying existing (eg. shipping options), but as I understand it, the Shopify API and these Python bindings don't support Shopify's 'local delivery' or 'local pickup' store/order options.

I'm building a sales channel app that requires this ability:

- fetch a store's local pickup and delivery option(s)/setting(s)
- place orders using these options

## Type

- [x] New feature
- [x] Changes to existing features

## Motivation

I cannot integrate my marketplace with Shopify until I can retrieve local each store's pickup and delivery settings, and use those settings to place orders through Shopify's APIs

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by mllemango** [comment]
Hey @jaddison! Have you looked into GraphQL for [local delivery](https://shopify.dev/docs/admin-api/graphql/reference/shipping-and-fulfillment/deliverymethodtype?api%5Bversion%5D=2021-01)? There are currently no REST support for this information yet, but we're working on releasing it in an upcoming version.

**Comment by jaddison** [comment]
@mllemango hi!

I was hoping to stick with REST, but am willing to evaluate GraphQL as a different approach, particularly if that gets more/earlier implementation love from Shopify? Would it support both getting the store's local delivery/pickup settings AND using those options when placing orders?

Thanks!

**Comment by mllemango** [comment]
GraphQL is definitely Shopify's preferred method of building APIs, take a look through https://shopify.dev/concepts/graphql as a starting point! 
I'll have to look into what it supports, I'm not too familiar with these endpoints.

**Comment by sagar-enoc** [comment]
> Hey @jaddison! Have you looked into GraphQL for [local delivery](https://shopify.dev/docs/admin-api/graphql/reference/shipping-and-fulfillment/deliverymethodtype?api%5Bversion%5D=2021-01)? There are currently no REST support for this information yet, but we're working on releasing it in an upcoming version.

Any updates on this feature please ?
