### ISSUE TITLE
Cannot retrieve inventory level

### ISSUE THREAD

**Issue by elmwoodelec** [Shopify/shopify_python_api#494]
# Issue summary

Write a short description of the issue here ↓

We cannot retrieve inventory levels using the following code:

		variant = shopify.Variant.find(variant_id)
		inventory_item_id = variant.inventory_item_id
		inventory_level = shopify.InventoryLevel(inventory_item_id, location_id)
		print inventory_level    #trying to test to see if it works

## Expected behavior

We would expect that the above would return an inventory level for the variant and location_id in question

## Actual behavior

What actually happens?

Traceback (most recent call last):
  File "./inv_test.py", line 42, in <module>
    print inventory_level
  File "/home/pi/.local/lib/python2.7/site-packages/shopify/resources/inventory_level.py", line 8, in __repr__
    return "%s(inventory_item_id=%s, location_id=%s)" % (self._singular, self.inventory_item_id, self.location_id)
  File "/home/pi/.local/lib/python2.7/site-packages/pyactiveresource/activeresource.py", line 917, in __getattr__
    raise AttributeError(name)
AttributeError: inventory_item_id

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
2.
3.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mllemango** [comment]
Hey @elmwoodelec, could you try adjusting the syntax of your code to look like:
```
inventory_level = shopify.InventoryLevel.find(
            inventory_item_ids=inventory_item_id, location_ids=location_id
        )
```

**Comment by elmwoodelec** [comment]
Thank you so much for your help.  I have been banging my head against a wall for several hours.  At least I'm not getting a syntax error now, but the above returns:

[inventory_level(inventory_item_id=xxx, location_id=xxx)]

(replace xxx with actual inventory item ID and location ID)

What am I missing to get the actual inventory on hand for the item in question?

**Comment by mllemango** [comment]
Np! Is thats the output of printing `inventory_level`? Try to print `inventory_level.__dict__`?

**Comment by elmwoodelec** [comment]
I get the following.  I've attempted to remove anything I shouldn't share publicly.

{'previous_page_url': None, '_previous': None, '_metadata': {'headers': {'x-shopify-stage': 'production', 'cf-cache-status': 'DYNAMIC', 'vary': 'Accept-Encoding', 'x-shopify-shop-api-call-limit': '1/40', 'x-shopid': '', 'report-to': '{"group":"network-errors","max_age":2592000,"endpoints":[{"url":"https://monorail-edge.shopifycloud.com/v1/reports/nel/20190325/shopify"}]}', 'http_x_shopify_shop_api_call_limit': '1/40', 'x-request-id': '-', 'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopi', 'x-content-type-options': 'nosniff', 'x-stats-apiclientid': '', 'x-shardid': '164', 'cf-request-id': '', 'transfer-encoding': 'chunked', 'referrer-policy': 'origin-when-cross-origin', 'x-sorting-hat-shopid': '', 'x-download-options': 'noopen', 'x-stats-apipermissionid': '', 'set-cookie': '; Expires=Tue, 22-Mar-22 20:47:57 GMT; Domain=elmwood-electronics.myshopify.com; Path=/; SameSite=Lax, _s2; Expires=Mon, 22-Mar-21 21:17:57 GMT; Domain=elmwood-electronics.myshopify.com; Path=/; SameSite=Lax, _shopify_y=e; Expires=Tue, 22-Mar-22 20:47:57 GMT; Domain=elmwood-electronics.myshopify.com; Path=/; SameSite=Lax, _shopify_s=; Expires=Mon, 22-Mar-21 21:17:57 GMT; Domain=elmwood-electronics.myshopify.com; Path=/; SameSite=Lax, _shopify_fs=2021-03-22T20%3A47%3A57Z; Expires=Tue, 22-Mar-22 20:47:57 GMT; Domain=elmwood-electronics.myshopify.com; Path=/; SameSite=Lax', 'nel': '{"report_to":"network-errors","max_age":2592000,"success_fraction":0.0001}', 'x-shopify-api-terms': 'By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms', 'x-shopify-api-version': '2021-01', 'date': 'Mon, 22 Mar 2021 20:47:57 GMT', 'cf-ray': '-IAD', 'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'x-stats-userid': '', 'content-security-policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https:/elf' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Finventory_levels&source%5Bsection%5D=admin_api&, 'x-dc': 'gcp-us-east1,gcp-us-east1', 'strict-transport-security': 'max-age=7889238', 'x-sorting-hat-podid': '164', 'server': 'cloudflare', 'connection': 'close', 'x-permitted-cross-domain-policies': 'none', 'x-frame-options': 'DENY', 'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400', 'content-type': 'application/json; charset=utf-8'}, 'pagination': {}, 'resource_class': <class 'shopify.resources.inventory_level.InventoryLevel'>}, '_current_iter': None, '_no_iter_next': True, '_next': None, 'next_page_url': None}

**Comment by mllemango** [comment]
Could you try iterating on the item and then calling __dict__? 
```
for item in inventory_level 
  print(item.__dict__)
```

**Comment by elmwoodelec** [comment]
OK that works.  Thank you again for your help.    I can see the quantity under u'available', in this case it is -20.  May I humbly suggest that there needs to be an easier way to obtain inventory level.  It used to be so easy when we could do it at the variant level.  Now that Shopify is killing that functionality it seems unnecessarily complicated, at least using the otherwise wonderful Shopify_Python_API calls.

{'_initialized': True, 'attributes': {u'available': -20, u'location_id': xxxx, u'updated_at': u'2020-10-28T12:21:20-04:00', u'admin_graphql_api_id': u'gid://shopify/InventoryLevel/xxxx?inventory_item_id=xxxx', u'inventory_item_id': xxxx}, 'errors': <pyactiveresource.activeresource.Errors object at 0xb4b95a10>, '_prefix_options': {}, 'klass': <class 'shopify.resources.inventory_level.InventoryLevel'>}

**Comment by mllemango** [comment]
No problem! Glad that helps.

I agree inventory management used to be a straightforward action. I would suggest bringing this up with Partner Support, there's not much we can do on our end except pass along this feedback to the support team anyways 😅

**Comment by elmwoodelec** [comment]
For anyone that stumbles upon this thread, here is code you can use to grab inventory level for a given variant and location_id.  I'm sure there is a more Python way to do this, but for now this works for us.

        variant = shopify.Variant.find(variant_id)
        inventory_item_id = variant.inventory_item_id
        inventory_level = shopify.InventoryLevel.find(inventory_item_ids=inventory_item_id, location_ids=location_id)
        quantity = inventory_level[0].__dict__["attributes"]["available"]

**Comment by iranpak** [comment]
Hi.
if i want call the api with multiple inventory_item_ids, should i give them as a list to the find method or as a comma separated string?
i mean:
shopify.InventoryLevel.find(inventory_item_ids=[id1, id2])
or
shopify.InventoryLevel.find(inventory_item_ids="id1,id2")?

regards
