### ISSUE TITLE
customer.orders() returns empty list

### ISSUE THREAD

**Issue by hethune** [Shopify/shopify_python_api#503]
# Issue summary

`customer.orders() ` returns an empty list

## Expected behavior

`customer.orders() ` should return the orders placed by the customer
## Actual behavior

`customer.orders() ` returns an empty list

## Steps to reproduce the problem

1. `order = shopify.Order.find(xxxxxxx)`
2. `customer = order.customer`
3. `customer.orders()` doesn't return the order

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by akhtariali** [comment]
+1

**Comment by akhtariali** [comment]
Mine is public.
