### ISSUE TITLE
Order.find with fields can break pagination

### ISSUE THREAD

**Issue by skomp** [Shopify/shopify_python_api#508]
# Issue summary

I have a query, that selects certain fields from the orders. The first page looks fine (`Order(<order id>)...`), the second is just empty (`Order(None)...`). This seems to only occur when more than just the id is selected.
```
# gives me a bunch of properly filled orders
page = Order.find(fields=['id', 'total_price_usd'], limit=25)
if page.has_next_page():
    # this doesn't
    page = page.next_page()
```

## Expected behavior
The second page should contain properly parsed order data.

## Actual behavior
As described above, I get a bunch of completely uninitialized orders on the second page.

## Steps to reproduce the problem

1. Query for shop orders like so: `page = Order.find(fields=['id', 'total_price_usd'], limit=1)`
2. Get the second page: `page2 = page.next_page()` and see 

## Reduced test case
I hope the above description is actionable enough.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mllemango** [comment]
Hey @skomp, could you try `fields='id,total_price_usd'` in your code and see if the second page looks right? Pyactiveresource parses these arguments poorly and I found this returned a better result on my end.
