### ISSUE TITLE
Support for AssignedFulfillmentOrder

### ISSUE THREAD

**Issue by imbue** [Shopify/shopify_python_api#509]
## Overview

Ability to use the full feature set provided by the fulfillment service API

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

I am building a 3rd party app which serves as a fulfillment service. It seems like the current version of this package doesn't allow to use the full power of the fulfilment service functionality provided by the Shopify API. Current workaround seems to be to register the fulfillments/create webhook and work from there.

Documentation reference:
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/assignedfulfillmentorder 

Is there anything I can do to help in the process?

**Comment by mllemango** [comment]
Hey @imbue, for sure! We try to keep this library in line with our ruby library, so it might help to reference what is currently done [there](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/assigned_fulfillment_order.rb). Also if you could add some tests that would be amazing.
