### ISSUE TITLE
How do I get sales data？

### ISSUE THREAD

**Issue by CachCheng** [Shopify/shopify_python_api#512]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
2.
3.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hi @CachCheng, thank you for your question.

You can use the Admin API (either via REST or GraphQL) to fetch order information for a shop. For more information, you can visit our [API documentation](https://shopify.dev/docs/admin-api/rest/reference/orders).

I'm closing this, as Github issues are meant for problems with the library's code, but you can discuss app development in general in the [Community Forums](https://community.shopify.com/c/App-Partner-Platform/ct-p/appdev).
