### ISSUE TITLE
How to use Limits

### ISSUE THREAD

**Issue by coler-j** [Shopify/shopify_python_api#519]
## Overview

How do you use `Limits` in conjunction with any of the resources? If you can provide an example, I will fill in the details and add some docs.

## Type

- [ ] New feature
- [x] Changes to existing features

**Comment by Ather23** [comment]
If you are referring to the `limit` parameter in the REST api then you can checkout any of the tests that uses the `limit` param.
Eg `test_get_metafields_for_product_with_params` 

![image](https://user-images.githubusercontent.com/2106106/132971500-767a8fd4-0f46-4d81-ac0d-705ad63fb124.png)
