### ISSUE TITLE
Unable to set Shopify API version via Shopify python SDK

### ISSUE THREAD

**Issue by Sentinel-Prime** [Shopify/shopify_python_api#522]
Hi there,

We recently upgraded the Shopify API version from 2020-04 to 2021-01.

But, we are receiving an email  that says -> Update your Shopify apps before July 1, 2021

we have found that when we are creating a private session, the Shopify API version is not getting set in the request URL.

## Expected behavior
The above code should hit a request on  https://store.myshopify.com/admin/api/2021-01/orders/327427347236423834782.json

## Actual behavior
but instead, it is hitting on ->  https://store.myshopify.com/admin/orders/327427347236423834782.json, and the version `2021-01` in URL is not getting set.

## Steps to reproduce the problem
```
import shopify
shop_url = "https://store.myshopify.com"/admin"
SHOPIFY_API_VERSION = '2021-01'
s_api_key = xxxxxxx

shopify.ShopifyResource.set_version(SHOPIFY_API_VERSION)
shopify.ShopifyResource.set_user(s_api_key)
shopify.ShopifyResource.set_password(s_password)
shopify.ShopifyResource.set_site(shop_url)
```

Python 3.6.8

ShopifyAPI==8.4.1

Django==2.2.1

**Comment by baumannalexj** [comment]
@mllemango is the sdk able to support this version? Are you able to clarify the latest Shopify API version this sdk supports?

Per the changelog:
- v8.0.4 supports API 2020-10 
- then 8.2.0 release supported "dynamic api versioning"
- then v8.4.0 Reverted the "Dynamic API Versioning" (https://github.com/Shopify/shopify_python_api/blob/master/CHANGELOG#L6-L7)

Thanks in advance!

**Comment by mllemango** [comment]
Yeah we tried out dynamic versioning but it created problems 😅 
We manually define the versions this library supports [here](https://github.com/Shopify/shopify_python_api/blob/master/shopify/api_version.py#L28). We're currently supporting 2020-01 to 2021-04. I'll remember to update the CHANGELOG in the future, sorry about that.

**Comment by baumannalexj** [comment]
that's great to know, thanks @mllemango !

**Comment by lowercase00** [comment]
Any new on supporting 2021-07?
