### ISSUE TITLE
File handler

### ISSUE THREAD

**Issue by trottomv** [Shopify/shopify_python_api#527]
## Overview

Recent shopify api 2021-07 version introduces the possibility to manage the files and storage in shopify. 

## Type

- Add File ShopifyResource handler

## Motivation

> It becomes very useful to integrate this function to have the possibility to take advantage of the shopify storage 

### Area

- File storage

**Comment by mllemango** [comment]
Hey 👋 , shopify resources map to some REST endpoints. Let me know if I'm misunderstanding here, but the file api is a graphql interface that you can query with the [graphql resource](https://github.com/Shopify/shopify_python_api/blob/master/shopify/resources/graphql.py).
