### ISSUE TITLE
Non-English letters in product handle are translated into similar English letters.

### ISSUE THREAD

**Issue by tcliuavenza** [Shopify/shopify_python_api#530]
# Issue summary

When I try to create/update a product handle with some letters similar to English letters but not English letters, it will be encoding into utf-8 and translated to English letters.

## Expected behavior

Handles should keep non-English letters

## Actual behavior

Handles are translated into similar English letters

## Steps to reproduce the problem
For example, I have a product with this issue https://avenzamaps-staging.myshopify.com/admin/products/6801031987370
1.product=shopify.Product.find(6801031987370)
2.product.handle = 'løno-friluftslivsområde'
3.product.save()
4.new_product=shopify.Product.find(6801031987370)
5product.handle
lono-friluftslivsomrade
Notice ø and å are translated into o and a.
The handle part of this request body is "handle": "l\\u00f8no-friluftslivsomr\\u00e5de"

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by Ather23** [comment]
I believe this standard Shopify behavior. Even if you create this product from the Shopify admin you will see similar results.
