### ISSUE TITLE
Not deploying to pypi

### ISSUE THREAD

**Issue by smubbs** [Shopify/shopify_python_api#531]
# Issue summary

Version 8.4.2 is not deploying to PYPI. 

## Expected behavior

Version 8.4.2 should deploy to PYPI

## Actual behavior

What actually happens?

Version 8.4.1 is the currently available version

---

## Checklist

- [ x] I have described this issue in a way that is actionable (if possible)

**Comment by sinejoe** [comment]
+1

**Comment by mllemango** [comment]
Finally deployed! Sorry for the delay everyone!
