### ISSUE TITLE
myshop domain incorrectly guessed at session creation time

### ISSUE THREAD

**Issue by mrdeveloperdude** [Shopify/shopify_python_api#535]
# Issue summary

When setting up a new session using the following code:

```python

@shopify_install_bp.route("/start")
def start():
    shopify_domain = request.args.get("shop")
    logger.info(f"Shopify app authentication started: shopify_domain={shopify_domain}, request.referrer={request.referrer}")
    shopify.Session.setup(api_key=current_app.config.get("shopify-api-key"), secret=current_app.config.get("shopify-api-secret"))
    shopify_session = shopify.Session(shop_url=shopify_domain, version=current_app.config.get("shopify-api-version"))
    permission_url = shopify_session.create_permission_url(shopify_scopes, url_for("shopify_install_bp.finish", _external=True))
    return render_template("shopify_install_bp/start.html", permission_url=permission_url)

```

on a store with the following domains:

|  |  |
|--------|-----|
| myshopify domain|something.myshopify.com |
| registered domain| other.com |

I encounter an error when I supply **other.com** as the shop query argument. The api then tries to install the app to **other.myshopify.com** which does not exist at all, resulting in an error.

## Expected behavior

I think the appropriate behaviour should be one of two things:

1. Fail with a message like "domain is not on the correct form (xxxx.myshopify.com)"
2. (Preferred) Actually look up the connected myshopify name for the domain and proceed authentication using that  

## Actual behavior

The api makes a best effort attempt to convert the domain to a myshopify domain such that **other.com** somehow becomes **other.myshopify.com**

## Steps to reproduce the problem

1. Create a store with a unique name (for example **exhibit_a.myshopify.com**)
2. Register a domain distinct from the store name to the store (for example **exhibit_b.com**)
3. Authenticate with api using parameter shop=**exhibit_b.com**

## Reduced test case

The code in the top of this issue is the actual production code we use to produce this error.

**Comment by mrdeveloperdude** [comment]
I have a utility function to get the myshopify domain given any domain. It works by inspecting the HTML of the page served by the domain:
```

import re
import requests
import logging
import urllib.parse
import fk.utils

logger = logging.getLogger(__name__)

shopify_re = re.compile("[\w\-_]*\.myshopify\.com")
shopify_var_re = re.compile('Shopify\.shop\s*\=\s*"([\w\-_]*\.myshopify\.com)"\s*;')


def normalize_shopify_address(raw_address):
    parsed = urllib.parse.urlparse(raw_address)
    if parsed.scheme not in ["http", "https"]:
        parsed = urllib.parse.urlparse("https://" + raw_address)
    if not parsed.hostname:
        return None, "No hostname"
    m = shopify_re.match(parsed.hostname)
    if m:
        return m.group(), ""
    if parsed.scheme not in ["http", "https"]:
        return None, "No scheme"
    test_url = f"{parsed.scheme}://{parsed.hostname}{parsed.path}"
    r = requests.get(test_url)
    if not r:
        return None, f"Error getting {test_url}: {r.http_code}"
    body = r.text
    # body = fk.utils.read_file("/tmp/test.html")
    m = shopify_var_re.search(body)
    if not m:
        return None, f"No match in {body}"
    address = m.group(1)
    return address, ""

```

**Comment by elkhayyat** [comment]
Thank you @mrdeveloperdude
I was just wondering how it is officially not solved yet.
Your solution helped us.
