### ISSUE TITLE
`from_` argument gives `"page_info": "Invalid Value"` during pagination

### ISSUE THREAD

**Issue by ccrvlh** [Shopify/shopify_python_api#544]
Trying to get all orders from a shop with something like this:
```python

all_orders = []
from_info = ""
total = shopify.Order.count(status="any")
c = 0
t0 = datetime.now()

while True:
    page = shopify.Order.find(from_=from_info, limit=5, status="any")
    c = c + len(page)
    all_orders.extend(page)
    if page.has_next_page():
        from_info = page.next_page_url
        print(f"Loaded {c} of {total} ({round(c/total, 2)}%)")
    else:
        break
elapsed = datetime.now() - t0
print(f"Got {len(all_orders)} in {elapsed}")
```
But his raises a `BadRequest` with : `Response(code=400, body="b'{"errors":{"page_info":"Invalid value."}}'" .... `
`page.next_page_url` is a `str`, I think that's what `from_` expects, but not really sure.

I tried parsing the URL and using `page_info`, something like this:

```python
while True:
    page = shopify.Order.find(page_info=from_info, limit=5, status="any")
    c = c + len(page)
    all_orders.extend(page)
    if page.has_next_page():
        from_info = urlparse(page.next_page_url)
        from_info = parse_qs(from_info.query)['page_info'][0]
        print(f"Loaded {c} of {total} ({round(c/total, 2)*100}%)")
    else:
        break
elapsed = datetime.now() - t0
print(f"Got {len(all_orders)} in {elapsed}")
```
But `page_info` doesn't work when using `status` (which is needed to retrieve all orders).
I'm not really that familiar with PyActiveResource, so it may be the case that I'm doing something wrong... not sure.

**Comment by beasyx0** [comment]
For anyone having this same problem, so was and I dont know why but my first function would work in dev but gave me the page_info error in prod. After just trying a new method everything was solved but I still don't know what the bug was. 

Anyway heres the working code from [here](https://stackoverflow.com/questions/43575659/how-to-get-all-product-id-from-shopify-python-api) (modified slightly):

`def get_all_shopify_resources(resource_type, **kwargs):

    all_resources = []

    resource_types = {
        'product': shopify.Product,
        'order': shopify.Order
    }

    resource = resource_types[resource_type]
    resource_count = resource.count(**kwargs)

    if resource_count > 0:
        page = resource.find(**kwargs)
        all_resources.extend(page)

        while page.has_next_page():
            page = page.next_page()
            all_resources.extend(page)

    return all_resources`

And because why not here's the one that works in dev but not in prod:

`def get_all_products():
    all_products = []
    proccessing = True
    page_from = None
    limit = 250
    while proccessing:
        page = shopify.Product().find(limit=limit, from_=page_from)
        for item in page:
            all_products.append(item)
        if page.has_next_page():
            page_from = shopify_products_page.next_page_url
        else:
            proccessing = False
    return all_products
`
