### ISSUE TITLE
Is there anyways to get a customer's password using RESTful APIs?

### ISSUE THREAD

**Issue by zhangmGoL** [Shopify/shopify_python_api#546]
When I query a customer's information using /admin/api/{api-version}/customers/{customer_id}.json, I found that the 'password' field is not included in the returned json results.

If I want to get the customer's password (used by a private-app verification with all accounts synced from my shopify store), is there anyway to implement?

Any help is sincerely appreciated.

Thanks and all.

**Comment by andyw8** [comment]
No this is not possible as it would be bad for security.
