### ISSUE TITLE
Mutation throwing an error  - b'{"errors":{"variables":"expected String to be a Hash"}}'

### ISSUE THREAD

**Issue by JJasperr** [Shopify/shopify_python_api#554]
# Issue summary

I run this mutation on Shopify GraphiQL app and its working fine. 
![Screenshot 2021-11-16 121110](https://user-images.githubusercontent.com/94431416/141933043-eb4f7a93-8687-4291-9b10-f46aa8330b25.png)

I run the mutation in Python with this code `spf.GraphQL().execute(bulkInventoryUpdate, variables = abc)`
where,
`bulkInventoryUpdate = """   
mutation inventoryBulkAdjustQuantityAtLocation($inventoryItemAdjustments: [InventoryAdjustItemInput!]!, $locationId: ID!) {
  inventoryBulkAdjustQuantityAtLocation(inventoryItemAdjustments: $inventoryItemAdjustments, locationId: $locationId) {
    userErrors {
      field
      message
    }
    inventoryLevels {
      available
    }
  }
}
"""`
and 
`abc = {
  "locationId": "gid://shopify/Location/64279675037" ,
  "inventoryItemAdjustments": [
  	{"inventoryItemId": "gid://shopify/InventoryItem/42774848667805", "availableDelta": -1.0}, 
  	{"inventoryItemId": "gid://shopify/InventoryItem/42774893559965", "availableDelta": -2.0}, 
  	{"inventoryItemId": "gid://shopify/InventoryItem/42774895591581", "availableDelta": 24.0}
  ]
}` 
with the actual variable `abc` being much much longer in my case, hundreds.
**Edit:** I just tested. It does not matter how many variables in there 3, 100 or 250 it doesnt work

## Expected behavior

It should update the quantity successfully

## Actual behavior

I was given the error -  `b'{"errors":{"variables":"expected String to be a Hash"}}'`

Im not sure if this is a bug or my formatting is wrong 

The rest of the error: 
`Traceback (most recent call last):
  File "c:\Users\DELL\Documents\VSC python\shopify_stockupdate download copy.py", line 280, in <module>
    r = spf.GraphQL().execute(bulkInventoryUpdate, variables = abc)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\shopify\resources\graphql.py", line 32, in execute
    raise e
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\shopify\resources\graphql.py", line 27, in execute
    response = urllib.request.urlopen(req)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request`

## Steps to reproduce the problem

1.  Use the same mutation in Python
2.  Location and id variable has to be changed 
3.  Run the mutation using spf.GraphQL().execute()

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by marcelo-isawitfirst** [comment]
I am getting the same issue:

```py
import shopify

class Shopify:
    API_KEY = ""
    PASSWORD = ""
    SHOP_URL = ""
    API_VERSION = "2022-01"

    def __init__(self):
        session = shopify.Session(Shopify.SHOP_URL, Shopify.API_VERSION, Shopify.PASSWORD)
        shopify.ShopifyResource.activate_session(session)
        
        result = shopify.GraphQL().execute('{ shop { name id } }')

        shopify.ShopifyResource.clear_session()


    def test(self):
        with shopify.Session.temp(Shopify.SHOP_URL, Shopify.API_VERSION, Shopify.PASSWORD):

            query = """mutation fileCreate($files: [FileCreateInput!]!) {fileCreate(files: $files) {files {alt} userErrors {field message}}}"""

            variables = "{\"files\":{\"alt\":\"TEST_MGR\",\"contentType\":\"IMAGE\",\"originalSource\":\"https://cdn.pixabay.com/photo/2016/11/29/04/19/ocean-1867285_960_720.jpg\"}}"

            result = shopify.GraphQL().execute(query, variables=variables)
            print(result)

s = Shopify()
s.test()
```
