### ISSUE TITLE
Can't call save() on a Variant

### ISSUE THREAD

**Issue by 541joehill** [Shopify/shopify_python_api#555]
# Issue summary

Write a short description of the issue here ↓
Ultimately, I am trying to:
1. Create a product.
2. Create it's variants
3. Update inventory for each variant

In my search I found this closed issue: https://github.com/Shopify/shopify_python_api/issues/476
which suggests I need to save my variant before I can access the associated variant's inventory_item_id.

## Expected behavior

What do you think should happen?
variant.save() to return successful and allow me to access the inventory_item_id attribute.

## Actual behavior

What actually happens?
calling variant.save() returns this error message:
```
  File "C:\Users\Trogdor\PycharmProjects\bc-to-shopify\functions.py", line 94, in createShopifyProducts
    variant.save()
  File "C:\Users\Trogdor\AppData\Local\Programs\Python\Python38-32\lib\site-packages\shopify\resources\variant.py", line 18, in save
    self._prefix_options["product_id"] = self.product_id
  File "C:\Users\Trogdor\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyactiveresource\activeresource.py", line 917, in __getattr__
    raise AttributeError(name)
AttributeError: product_id
```

I have tried calling save() on the Product itself before calling save() on the variant to no avail.

## Steps to reproduce the problem

1. For each product I am creating
2. Create each of it's variants
3. Save the variant

## Reduced test case

Psuedo code (I am pulling in products from BigCommerce):

```
for product in big_commerce_products:
   shopify_product = shopify.Product()
   for options in product:
       variant = shopify.Variant()
       shopify_product.variants.append(variant)
       shopify_product.save()
       variant.save()
```

---

## Checklist

I have described this issue in a way that is actionable (if possible)

**Comment by DC1MK** [comment]
Try to use the add_variant method, its prt of the product resource.

**Comment by 541joehill** [comment]
Hi DC1MK, thanks for the suggestion. Calling add_variant() seems to have solved the issue of the Product's product_id throwing an error. However, this method did **not** actually create variants within Shopify. 
Calling  shopify_product.variants.append(variant) **does** create the product's variants. Which is strange behavior.
