### ISSUE TITLE
Outdated content on open source site (`shopify.github.io/shopify_python_api`)

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify_python_api#559]
As noticed by @catlee, the content at http://shopify.github.io/shopify_python_api/ is very outdated because it's based on this branch which hasn't been updated since 2016:

https://github.com/Shopify/shopify_python_api/tree/gh-pages

**Comment by morebebop** [comment]
I'd love to jump on this as a first issue, but it looks like the webpage you mentioned (http://shopify.github.io/shopify_python_api/) is not updated through this repo. I'm new to python/open source so please let me know how I can best assist.

**Comment by mllemango** [comment]
Its not immediately obvious, the github page is updated through this repo's `gh-pages` branch that is linked above. 
Instead of basing any changes on master, you should use `gh-pages` as your branch and make changes off there.
