### ISSUE TITLE
Is the support for python 2 completly removed?

### ISSUE THREAD

**Issue by rutuja-zinrelo** [Shopify/shopify_python_api#565]
I am sorry for raising a query as an issue here. But I have a question as under, 
I am currently using Python2.7 along with shopify_python_api version 8.4.2. Will I be able to upgrade to the next version of shopify_python_api without upgrading to python 3 ?

**Comment by mllemango** [comment]
Hey @rutuja-zinrelo, we've officially dropped python 2 support but theres been no code changes that would affect the older version so nothing should stop you from using 2.7. That said, we are no longer testing against 2.7 so use at your own caution.
