### ISSUE TITLE
Saving an existing order will create a new order instead of updating the existing one

### ISSUE THREAD

**Issue by Rahza** [Shopify/shopify_python_api#566]
# Issue summary

I'm retrieving a list of existing orders.

`orders = shopify.Order.find(tag="imported")`

I then update each order's `financial_status` and save it:

```
for order in orders:
    order.financial_status = "paid"
    order.save()
```

## Expected behavior

I expect the order's `financial_status` to be updated.

## Actual behavior

Instead, a new copy of the order is created (with the updated `financial_status`)

---

## Checklist

- [X] I have described this issue in a way that is actionable (if possible)

**Comment by mllemango** [comment]
Hey @Rahza, according to the [docs](https://shopify.dev/api/admin-rest/2022-01/resources/order#resource_object) it looks like the `financial_status` can only be set during creation, so it is not possible to update it.
