### ISSUE TITLE
Application charge won't accept price of zero (usage-based only billing)

### ISSUE THREAD

**Issue by lowercase00** [Shopify/shopify_python_api#568]
# Issue summary
While using the API for the "RecurringApplicationCharge" with price 0.0 (usage based only), the response I get is: 
```python
{'base': recurring_application_charge(None), 'errors': {'price': ['must be greater than zero']}}
```

## Expected behavior

On the REST API Documentation, however the docs state:

> A common billing scenario is to charge only usage-based fees, without a flat recurring monthly fee. To charge only usage-based fees without a recurring monthly fee, first create a [recurring application charge](https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge/) with a price of $0.00 and then apply the usage charge.

It is expected that creating a RecurringApplicationCharge with price 0 should be allowed.

## Actual behavior

RecurringApplicationCharge price must be greater than zero.

## Steps to reproduce the problem

```python
payload = dict(
    name=billing_plan.name,
    price=billing_plan.price,
    return_url=return_url,
    terms=billing_plan.terms,
    trial_days=billing_trial_days,
    test=test
)

application_charge = shopify.RecurringApplicationCharge.create(payload)
print(application_charge.errors.__dict__)
> {'base': recurring_application_charge(None), 'errors': {'price': ['must be greater than zero']}}
```

## Extra

Would also suggest a more clear documentation regarding errors, and error messages. You need to specifically access the `errors` attribute to know whats going on - I didn't find this detail anywhere in the documentation.

**Comment by chehodgins** [comment]
I ran into this a few days ago.

See the documentation in [UsageCharge](https://shopify.dev/api/admin-rest/2021-07/resources/usagecharge#top):
> A common billing scenario is to charge only usage-based fees, without a flat recurring monthly fee. To charge only usage-based fees without a recurring monthly fee, first create a [recurring application charge](https://shopify.dev/docs/admin-api/rest/reference/billing/recurringapplicationcharge/) with a price of $0.00 and then apply the usage charge.
> 
> You need to include the capped_amount and terms properties in the body of your request when you create a recurring application charge with a price of $0.00.

Once I added `capped_amount` and `terms` I was able to create the Recurring Application Charge.
