### ISSUE TITLE
API error "Could not acquire lock on fulfillment" handled incorrectly

### ISSUE THREAD

**Issue by tschottdorf** [Shopify/shopify_python_api#59]
When saving a fulfillment, every now and then a fulfillment.save() call will result in:

Response(code=422, body="{"errors":"Could not acquire lock on fulfillment."}", headers=...)

This then goes through from_json error handling to from_hash, but from_hash is called with the string "Could not acquire lock on fulfillment".

This seems very much parallel to
https://github.com/Shopify/shopify_api/issues/103

and should probably be fixed. Right now it will raise a KeyError and the user will be completely in the dark as to what went wrong.

Best,
Tobias

**Comment by jamiemtdwyer** [comment]
Closing this in favour of https://github.com/Shopify/shopify_python_api/issues/127 which explains the issue in a more general manner.
