### ISSUE TITLE
How to get the customer orders ordered by created date?

### ISSUE THREAD

**Issue by Tomperez98** [Shopify/shopify_python_api#597]
I currently have this code thinking that `order_id` goes incrementally. But it seems that's not the case
```python
customer_orders = shopify.Order.find(
            customer_id=customer_id, status=status, limit=limit, order="id asc"
        )
```

What would be the correct order by field?

**Comment by diegodiome** [comment]
Hi, you can use 'created_at' key in order parameter.

Example:
`shopify.Order.find(limit=50, order='created_at asc')`
