### ISSUE TITLE
Setting timeout in GraphQL

### ISSUE THREAD

**Issue by armindelgosar** [Shopify/shopify_python_api#630]
## Overview/summary

It will be great if other projects can set a timeout for GraphQL resource class
...

## Motivation

> What inspired this enhancement?

Sometimes while executing graphql queries or requests remain in pending state and it can be harmful to the server. but in GraphQL class we cannot set an initial timeout, though the class uses urllib and it has a configurable timeout field. In our case, we were forced to create another inherited class that overrides execution and sets timeout.
...

### Area
shopify/resources/graphql.py

- [X] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [X] I have described this enhancement in a way that is actionable (if possible)

**Comment by daniel-gomes** [comment]
Would love to see this too, can even provide a PR if wanted? Could be as simple as adding a timeout parameter to `GraphQL.execute()` and passing that to the `urllib.request.urlopen()` call.
