### ISSUE TITLE
'dict' object has no attribute 'attributes'. Trying to create a new product with multiple variants

### ISSUE THREAD

**Issue by tajbowness** [Shopify/shopify_python_api#638]
# Issue summary

Write a short description of the issue here ↓
Trying to create a new blank product with multiple variants.

Code:

    product = shopify.Product()

    product.title = input_title
    product.body_html = "<strong>Good snowboard!</strong>"
    product.vendor = "Burton"
    product.product_type = "Snowboard"
    product.status = "draft"

    product.variants = [{
        'price': '19.99',
        'option1': 'Variant 1',
        'position': 1,
        'inventory_quantity': 50,
        "inventory_management": "shopify",
        'sku': "TEST1"
    },{
        'price': '19.99',
        'option1': 'Variant 2',
        'position': 2,
        'inventory_quantity': 50,
        "inventory_management": "shopify",
        'sku': "TEST2"
    }]

    product.save()

## Actual behavior

What actually happens?

Output:
Traceback (most recent call last):
  File "/Users/Work/PycharmProjects/Shopify Project/Create Blank Products.py", line 46, in <module>
    product.save()
  File "/Users/Work/PycharmProjects/Shopify Project/venv/lib/python3.10/site-packages/shopify/resources/product.py", line 39, in save
    if "inventory_quantity" in variant.attributes:
AttributeError: 'dict' object has no attribute 'attributes'

Although the inventory_quantity is included. it still doesn't work. Changing the "product.variants[{}]" to "product.variant{}" works properly but from what I've tried it can only create one variant.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by Meak-Li** [comment]
Hi, I'm facing the same issue. Looking at the save method it seems that it's unable to find the "attributes" attribute for the variant. I tried a few workarounds but nothing.

I was able to create the product correctly with variants by building the json and making the request with the requests library.
