### ISSUE TITLE
ModuleNotFoundError: No module named 'shopifyapi'

### ISSUE THREAD

**Issue by JonhSilver** [Shopify/shopify_python_api#645]
C:\Users\>pip install ShopifyAPI
Requirement already satisfied: ShopifyAPI in c:\python3\lib\site-packages (12.2.0)
Requirement already satisfied: PyYAML in c:\python3\lib\site-packages (from ShopifyAPI) (6.0)
Requirement already satisfied: six in c:\python3\lib\site-packages (from ShopifyAPI) (1.16.0)
Requirement already satisfied: PyJWT>=2.0.0 in c:\python3\lib\site-packages (from ShopifyAPI) (2.6.0)
Requirement already satisfied: pyactiveresource>=2.2.2 in c:\python3\lib\site-packages (from ShopifyAPI) (2.2.2)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\>D:\test.py
Traceback (most recent call last):
  File "D:\test.py", line 1, in <module>
    from shopifyapi import ShopifyAPI
ModuleNotFoundError: No module named 'shopifyapi'

**Comment by cal97g** [comment]
you need to just `import shopify`
