### ISSUE TITLE
Unable to paginate Customers

### ISSUE THREAD

**Issue by MiPnamic** [Shopify/shopify_python_api#671]
# Issue summary

I have more than 4k customers I need to cycle through all of them but I can't paginate.

## Expected behavior

customers = shopify.Customer.search(status='any', fields="id,email,metafields", query='orders_count:>=1', limit=250)
I expect the customers object to have the has_next_page()

## Actual behavior

When I ran:
<details>
customers.has_next_page()
</details>
I got:
<details>
AttributeError: 'Collection' object has no attribute 'has_next_page'
</details>

## Steps to reproduce the problem

1. execute a search for more than 250 customers

**Comment by ScottRoach** [comment]
The search methods don't return PaginatedCollection results.

You can either cheat and mimic it by doing the following:
```python
args = {
    'status': 'any',
    'fields': 'id,email,metafields',
    'query': 'orders_count:>=1',
    'limit': 250
}
customers = shopify.Customer.find(from_=shopify.Customer._custom_method_collection_url('search', args), **args)
if customers.has_next_page():
    customers = customers.next_page()
```

Or you can patch the native method:
```python
"""
Code that runs at startup
"""
import shopify

class Customer(shopify.Customer):
    @classmethod
    def search(cls, **kwargs):
        return cls.find(from_=cls._custom_method_collection_url('search', kwargs), **kwargs)

# Actually patch the method
shopify.Customer = Customer

"""
Code that searches users
"""
customers = shopify.Customer.find(status='any', fields="id,email,metafields", query='orders_count:>=1', limit=250)
if customers.has_next_page():
    customers = customers.next_page()
```

**Comment by MiPnamic** [comment]
thank you @ScottRoach, that answered to my needs.

I want also to point out that the Help over the Shopify.customer.search metod state:

`Help on method search in module shopify.resources.customer:

search(**kwargs) method of shopify.base.ShopifyResourceMeta instance
    Search for customers matching supplied query
    
    Args:
       order: Field and direction to order results by (default: last_order_date DESC)
       query: Text to search for customers
       page: Page to show (default: 1)
       limit: Amount of results (default: 50) (maximum: 250)
       fields: comma-separated list of fields to include in the response
    Returns:
       A Collection of customers.`
       
      I also tried to use that "page" but regardless the API version used the results was the same:

      `BadRequest: Response(code=400, body="b'{"errors":{"page":"page cannot be passed. See [https:\\/\\/shopify.dev\\/api\\/usage\\/pagination-rest](https://shopify.dev///api///usage///pagination-rest) for more information."}}'"`
