### ISSUE TITLE
Support updating Metaobjects

### ISSUE THREAD

**Issue by felpsio** [Shopify/shopify_python_api#676]
## Overview

The library doesn't seem to support metaobjects. At least I wasn't able to find the feature in the repo. I'm creating a script to update a metaobject daily in my store and this information is being used by my website.

## Type

- [x ] New feature

## Motivation

> What inspired this feature request? What problems were you facing?

My store has a big number of possible filters for products and most of them comes from automated sources. So instead of hardcoding I'm storing the possible combinations in a metaobject that I can use to show in the filters. Be able to update the metaobject using this library would make my life much easier

I would need something like:
```
metaobject = shopify.Metaobject.find(resource_id=ID)
metaobject.fieldValue = NEW_VALUE
metaobject.save(update=True)
```

### Area

- metaboject

## Checklist

- [ x] I have described this feature request in a way that is actionable (if possible)

**Comment by ScottRoach** [comment]
Best I can tell Shopify doesn't have a RESTful api endpoint for metaobjects, so your example won't be possible.

You will just need to use this library to access [metaobjects](https://shopify.dev/docs/api/admin-graphql/2023-07/queries/metaobject) via the [GraphQL api](https://github.com/Shopify/shopify_python_api#graphql) instead.
