### ISSUE TITLE
shopify.Option.create pyactiveresource.connection.ClientError

### ISSUE THREAD

**Issue by chiliangpi** [Shopify/shopify_python_api#682]
# I want create Option for the upload product, but I encountered this error：
## Actual behavior
option_data = {
    "name": "Color",
    "position": 1,
    "values": ["Red", "Blue", "Green"]
}
new_option = shopify.Option.create(option_data)

pyactiveresource.connection.ClientError: Response(code=406, body="b''", headers={'Date': 'Fri, 29 Sep 2023 18:13:11 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'X-Sorting-Hat-PodId': '321', 'X-Sorting-Hat-ShopId': '83670270274', 'Referrer-Policy': 'origin-when-cross-origin', 'X-Frame-Options': 'DENY', 'X-ShopId': '83670270274', 'X-ShardId': '321', 'X-Stats-UserId': '', 'X-Stats-ApiClientId': '62867505153', 'X-Stats-ApiPermissionId': '645906170178', 'X-Shopify-API-Terms': 'By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms', 'X-Shopify-API-Version': '2022-10', 'X-Shopify-API-Version-Warning': 'https://shopify.dev/concepts/about-apis/versioning', 'HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT': '1/40', 'X-Shopify-Shop-Api-Call-Limit': '1/40', 'Server-Timing': 'processing;dur=38', 'X-Shopify-Stage': 'production', 'Content-Security-Policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=error_404&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Ferrors&source%5Bsection%5D=admin_api&source%5Buuid%5D=145634f1-ed7d-4834-b5ee-b85751248226", 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block; report=/xss-report?source%5Baction%5D=error_404&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Ferrors&source%5Bsection%5D=admin_api&source%5Buuid%5D=145634f1-ed7d-4834-b5ee-b85751248226', 'X-Dc': 'gcp-asia-southeast1,gcp-us-east1,gcp-us-east1', 'X-Request-ID': '145634f1-ed7d-4834-b5ee-b85751248226', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=eM%2BJ%2F1FSrz5HYkMwf2A%2FdpeBUjDNFpyY7Nrj%2FUu7b1QnD4JHh5kekI86nUbGTz4VWKV56evynnEvicQrm774wM7jsU%2FIXLuHZTt4IzfhASqEiIJ%2FZBigzY0nDUWCZBVD7gXSBxOGwRw%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '80e632db18c340e8-SIN', 'alt-svc': 'h3=":443"; ma=86400'}, msg="Not Acceptable")

Thanks

**Comment by ScottRoach** [comment]
You shouldn't be using the create method on this. Instead do the following:
```
option_data = {
    "name": "Color",
    "position": 1,
    "values": ["Red", "Blue", "Green"]
}
new_option = shopify.Option(option_data)
```

I'm pretty sure you can then append it to your product's options array.
