### ISSUE TITLE
When is 2023-7 api version releasing

### ISSUE THREAD

**Issue by KushGoyal** [Shopify/shopify_python_api#684]
## Overview/summary

Support the latest API version.

## Motivation

Currently shopify version is 2023-10 and the sdk is still stuck on 2023-04

### Area

The `api_version.py` should be updated to add `2023-07` and `2023-10`

**Comment by outring** [comment]
If you just need to be on the latest API version without the library actually supporting it you can get away with just `ApiVersion.define_version(Release("2023-10"))` on the app start. You need to test if doesn't break anything for you, obviously, do it on your own risk

**Comment by leocxy** [comment]
> If you just need to be on the latest API version without the library actually supporting it you can get away with just `ApiVersion.define_version(Release("2023-10"))` on the app start. You need to test if doesn't break anything for you, obviously, do it on your own risk

I like your idea! I suppose that is why people are chasing the latest version because we don't want to take the risk.
