### ISSUE TITLE
pyactiveresource.connection.Error: Not Found: fulfillments.json when creating fulfillment

### ISSUE THREAD

**Issue by stockpilothq** [Shopify/shopify_python_api#685]
# Issue summary

We get this error 
pyactiveresource.connection.Error: Not Found: https://***.myshopify.com/admin/api/2023-04/orders/***/fulfillments.json when we try to create a fulfilment via shopify.Fulfillment.

## Expected behavior

Fulfilment should be created

## Actual behavior

We get this error message: pyactiveresource.connection.Error: Not Found: https://***.myshopify.com/admin/api/2023-04/orders/***/fulfillments.json

We use this code to create a fulfilment
`    shopify.ShopifyResource.activate_session(session)
    
    shopify_order = shopify.Order.find(order_id)

    fulfillment = shopify.Fulfillment({'order_id': shopify_order.id, 'line_items': shopify_order.line_items,
                                       'location_id': location.location_id})

    fulfillment.tracking_company = tracking_company
    fulfillment.tracking_number = tracking_number
    fulfillment.tracking_url = tracking_url
    fulfillment.notify_customer = True
    fulfillment.save()

    shopify.ShopifyResource.clear_session()
`
It always went well, but the last shops using our software get the error. We found a few threads with issues creating fulfilment and following advises from there did not solve it yet for us.

**Comment by 20174103151** [comment]
hi，Have you solved it? I encountered the same problem

**Comment by stockpilothq** [comment]
we rewritten with python requests

`    # Get fulfillment id and location id
    fulfillment_orders = requests.get(f"{shop_url}/orders/{order_id}/fulfillment_orders.json", headers=headers).json()
    fulfillment_id = fulfillment_orders['fulfillment_orders'][0]['id']
    location_id = requests.get(f"{shop_url}/locations.json", headers=headers).json()['locations'][0]['id']

    # Get fulfillment order line items
    fulfillment_order_line_items = [
        {
            'id': item['id'],
            'quantity': item['quantity']
        }
        for item in fulfillment_orders['fulfillment_orders'][0]['line_items']
    ]

    payload = {
        "fulfillment": {
            "notify_customer": False,
            "location_id": location_id,
            "tracking_info": {
                "url": tracking_url,
                "company": tracking_company,
                "number": tracking_number
            },
            "line_items_by_fulfillment_order": [
                {
                    "fulfillment_order_id": fulfillment_id,
                    "fulfillment_order_line_items": fulfillment_order_line_items
                }
            ]
        }
    }

    response = requests.post(f"{shop_url}/fulfillments.json", json=payload, headers=headers)
    return response.json()`

**Comment by Olcaey** [comment]
Having the same issue on version 2024-01 and could not find any solution yet...
