### ISSUE TITLE
API Version is not working greater then 2023-04

### ISSUE THREAD

**Issue by itsmekhmtz** [Shopify/shopify_python_api#692]
shopify.api_version.VersionNotFoundError

Min APi version is support 2023-04 which is deprecated form Shopify side

**Comment by arneb** [comment]
I can confirm the issue ... :-) 
Please upgrade the package for newer api versions.

**Comment by wmurphy** [comment]
+1

**Comment by flemmard-hub** [comment]
#669  should fix it for 2023-07, please @shopify-admins ? is this still maintained ?

**Comment by kevinbroomepetlab** [comment]
+1

**Comment by melvidal** [comment]
I really hope this is still maintained 😰

**Comment by itsmekhmtz** [comment]
can any one able to update the version of library

**Comment by nbenouss** [comment]
I have just sent an email to engineering@shopify.engineering , try also to contact them :) the more they see community activity the more likely we are to see the PR accepted.
