### ISSUE TITLE
Package Version 12.4.0 shows released in CHANGELOG but not available in PyPi

### ISSUE THREAD

**Issue by karanaggarwal1** [Shopify/shopify_python_api#696]
# Issue summary

Package Version 12.4.0 shows released in CHANGELOG but not available in PyPi

## Expected behavior

ShopifyAPI==12.4.0 should be available on https://pypi.org/project/ShopifyAPI/

## Actual behavior

ShopifyAPI==12.3.0 is the latest available version on pypi currently

## Steps to reproduce the problem

1. Do pipenv install ShopifyAPI==12.4.0
2. See the error message come up for missing versions

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by simobasso** [comment]
@karanaggarwal1 it seems there is a problem in the [pypi deployment](https://github.com/Shopify/shopify_python_api/pull/695#issuecomment-1889593779)

@mllemango 👋  do you think is possible, only for this time considered the situation, do a manual deployment on pypi?

In this way everyone can get the access to the pacakge from pypi, and then you can fix the pipeline at your own pace ☺️ wdyt?

**Comment by mllemango** [comment]
It has been released 🎉 
Apologies for the wait everyone
