### ISSUE TITLE
I cannot find the abandoned checkouts endopoint

### ISSUE THREAD

**Issue by AntonioVentilii-IRIIDE** [Shopify/shopify_python_api#707]
Dear all,

Maybe I missed something obvious, but how can I use the endpoint `checkouts`?

Docs here:
[Abandoned Checkouts](https://shopify.dev/docs/api/admin-rest/2024-01/resources/abandoned-checkouts)

**Comment by AntonioVentilii** [comment]
> Dear all,
> 
> Maybe I missed something obvious, but how can I use the endpoint `checkouts`?
> 
> Docs here: [Abandoned Checkouts](https://shopify.dev/docs/api/admin-rest/2024-01/resources/abandoned-checkouts)

marking
