### ISSUE TITLE
request online access token

### ISSUE THREAD

**Issue by vt-rc** [Shopify/shopify_python_api#714]
## Overview

I am not sure why shopify repeatedly ignore people's request to add support for online access token into the python sdk....
there were many previous issues opened for this but ignored completely.

#484
 #700

all the other shopify sdk have support for online access token.
It is as if shopify hates python....when it is far more popular programming language than ruby

...

## Type

- [x] New feature
- [x] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?
can't build app without it and it should be sooooo easy to add.
...

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by vt-rcheng** [comment]
don't go stale
