### ISSUE TITLE
Mypy Support

### ISSUE THREAD

**Issue by WillAyd** [Shopify/shopify_python_api#729]
## Overview/summary

It would be great for the Shopify API to support mypy, whether through py.typed or a separate stubs library

## Motivation

> What inspired this enhancement?

Many other Python packages offer some support for this, even in very limited form, to assist with static type checking and IDE experience

### Area

N/A

---

## Checklist

- [X] I have described this enhancement in a way that is actionable (if possible)

**Comment by SamuelT-Beslogic** [comment]
Hi. We'd be interested in using a fully typed API as well. 

In the mean time, I'm working around that issue this way:
```ini
[mypy-app.core.services.shopify.*]
# https://github.com/Shopify/shopify_python_api/issues/729
disallow_untyped_calls = False

[mypy-shopify.*]
# https://github.com/Shopify/shopify_python_api/issues/729
follow_untyped_imports = True
```
