### ISSUE TITLE
Mssing cli tests

### ISSUE THREAD

**Issue by kevinhughes27** [Shopify/shopify_python_api#74]
We have tests for the command line interface in the ruby gem:
https://github.com/Shopify/shopify_api/blob/master/test/cli_test.rb

We haven't ported them here

**Comment by asiviero** [comment]
It looks like this file has been removed from the original repo

**Comment by kevinhughes27** [comment]
Yeah we split the cli into its own project. Also means that we probably shouldn't have it as part of this repo anymore
