### ISSUE TITLE
Release a new version of the package in PyPi to address API version 2024-10 public available

### ISSUE THREAD

**Issue by tyzhnenko** [Shopify/shopify_python_api#742]
## Overview/summary

Recently, the PR #737 with support of 2024-10 has been merged. It makes sense to make it public available in PyPI.

## Motivation

> What inspired this enhancement?

Shopify released 2024-10 a month ago. But the latest public version of ShopifyAPI package hasn't been supported it yet.

---

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by tyzhnenko** [comment]
Hey @lizkenyon,

Could you assist with releasing a new version as well, please?

TIA

**Comment by lizkenyon** [comment]
Hey @tyzhnenko 👋 

We will try to get a release out tomorrow. Thanks for your patience!

**Comment by matteodepalo** [comment]
Hi @tyzhnenko, we've just release a new version!
