### ISSUE TITLE
Support for independently creating/modifying product images.

### ISSUE THREAD

**Issue by gavinballard** [Shopify/shopify_python_api#88]
Please correct me if I'm wrong, but at the moment the only way to create/update product images through the Python API is directly through a POST/PUT call to the product endpoint.

As per the [Shopify API documentation on product images](http://docs.shopify.com/api/product_image), we should be able to make POST and PUT calls directly to `/admin/products/#{id}/images.json` and `PUT /admin/products/#{id}/images/#{id}.json`. However, this doesn't seem to work currently with the API as the prefix for the `Image` class isn't properly being built. Thus, something like this...

```python
image = shopify.Image()
image.src = "http://example.com/example.png"
image.product_id = 123456789
image.save()
```

... tries to POST to `/admin/products//images.json` which returns a 406.

Looking at the source, I think a fix would be to implement the `prefix()` class method, similar to what's been done with the `Variant` class. Just wanted to run this by folks who might be more familiar with this to see if that might be a valid solution.

**Comment by kevinhughes27** [comment]
that sounds like the correct approach to me.

**Comment by gavinballard** [comment]
Cool, thanks for the feedback. I have a workaround in place for the moment but when I find the time I'll fix this up and shoot through a PR.

**Comment by kevinhughes27** [comment]
np thanks for helping out!
