### ISSUE TITLE
Cannot create order with transactions

### ISSUE THREAD

**Issue by kishinmanglani** [Shopify/shopify_python_api#90]
`order.transactions = [{"amount":20.0,"kind":"capture","status":"success", "source_name" : "other"}]`

This doesn't work. 

If I do `order.transaction = [{"amount":20.0,"kind":"capture","status":"success", "source_name" : "other"}]` intercept the request and add an s to transaction it works. 

I think this is because the order model has a method named `transactions`

**Comment by kevinhughes27** [comment]
It probably has to do with the prefix options thats what I would check out

**Comment by kishinmanglani** [comment]
not sure what you mean. i found a workaround: `order.attributes['transactions']`

**Comment by kevinhughes27** [comment]
@kishinmanglani pyactiveresource has a lot of logic to determine if items are nest models and what their path should be. One way to set these options is using the prefix options and that is one reason why there is a mismatch on the pluralization.

what do the object attributes look like if you do order.transactions = ...?

**Comment by juanmhidalgo** [comment]
I've the same problem. 
To make it work I initialize the Order() with a dict and works fine.
```
def _create_order(p_customer, address, line_items, tags=['QA']):
    total = 0

    for li in line_items:
        total += li['price']

    order = {
        'customer': p_customer,
        'shipping_address': address,
        'billing_address': address,
        'line_items': line_items,
        'tags': tags,
        'source_name': 'QA',
        'financial_status': 'paid',
        'transactions': [
            {
                'test': True,
                'gateway': 'bogus',
                'kind': 'sale',
                'amount': total
            }
        ]
    }

    s_order = shopify.Order(order)
    return s_order
```
