### ISSUE TITLE
Getting list of created webhooks

### ISSUE THREAD

**Issue by DLBurton** [Shopify/shopify_python_api#93]
Hi there,

I may be missing something really obvious but I seem to be struggling to find documentation on how I can call the list of created webhooks. I know I can create a webhook using...

         product_hook = shopify.Webhook()
        product_hook.topic ='order/payment'
        product_hook.address = settings.SHOPIFY_APP_URL + '/webhooks/order-payments/'
        product_hook.format = 'json'

How do I then check that this has suceeded?

**Comment by gavinballard** [comment]
After your code above, you'll have to call `product_hook.save()` to actually push the Webhook to Shopify (that call should return `True`) on success, and your `product_hook` object should be updated with the ID Shopify generated for it.

If you want to get a list of all Webhooks your application has created, you can do that with `shopify.Webhook.find()`.

**Comment by DLBurton** [comment]
Hi Gavin,

Thank you for such a quick response. I have tried just that but don't seem to be having any success. This is an example of the code i'm using

@login_required
def home(request):

    # https://github.com/Shopify/shopify_python_api
    # to work with another shop must clear current.

    shopify.ShopifyResource.clear_session()


    with request.user.session:
        product_hook = shopify.Webhook()
        product_hook.topic ='order/payment'
        product_hook.address = settings.SHOPIFY_APP_URL + '/webhooks/order-payments/'
        product_hook.format = 'json'
        product_hook.save()

        print shopify.Webhook.find()


and I get returned a empty array 

    []

Have I missed a step here? 

Thanks Darren

**Comment by gavinballard** [comment]
Okay, so this is all good and working now? :)

**Comment by kevinhughes27** [comment]
I am going to close since this isn't actually an issue with the library. @DLBurton questions like this are better asked on the api forum where more people are watching to help answer questions!
