### ISSUE TITLE
GET Metafields for a Product

### ISSUE THREAD

**Issue by alexclarkofficial** [Shopify/shopify_python_api#95]
Is there a way to GET the metafields for a particular product if I have the product ID?  Couldn't find it in the docs.

**Comment by kevinhughes27** [comment]
yup! 
GET ...  /admin/products/632910392/metafields.json

**Comment by alexclarkofficial** [comment]
There's no way using the library though?  I have to make a GET request?

**Comment by kevinhughes27** [comment]
should be just a `.metafields` on product. Have a look at the source product has the metafields mixin
